### ISSUE TITLE
API Crashes/Hangs after many requests

### ISSUE THREAD

**Issue by Stefar77** [Icinga/icinga2#5408]
We have many passive services that get updated by a single active check on a host.
When we switch from using sockets to API to send passive results the API will crash within minutes.

## Expected Behavior

When pushing lots and lots of events via API it should not hang.

## Current Behavior

Pushing many passive results to Icinga2 via API results in process hang, possibly the Icinga2 process itself will crash a while later without leaving a crash log.
The only way to get API running again is kill -KILL {PID} or killall -KILL icinga2 and restarting and not stress the API / use socket to send passive check results.

## Possible Solution

None found yet, tried 66c0746. It does seem to make the API a lot faster but it will still crash.

## Steps to Reproduce (for bugs)

1. Add ~40 hosts with 10 Passive services and 1 Active service
2. Make the Active service send a couple of passive results to its host via API
3. Select the 40 active services in the GUI and press Check Now
4. You have killed the API

## Context

Trying to upgrade pollers to use API instead of sockets so they can use feedback and stuff.

## Your Environment

* Version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.3-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr/local
  Sysconf directory: /usr/local/etc
  Run directory: /var/run
  Local state directory: /var
  Package data directory: /usr/local/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /var/run/icinga2/icinga2.pid

System information:
  Platform: Unknown
  Platform version: Unknown
  Kernel: FreeBSD
  Kernel version: 11.0-RELEASE-p9
  Architecture: amd64

Build information:
  Compiler: Clang 3.8.0
```
* Operating System and version:
```
FreeBSD 11.0-RELEASE-p9 #0: Tue Apr 11 08:48:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC 
```
* Enabled features (`icinga2 feature list`):
```
api checker command graphite ido-mysql livestatus mainlog notification syslog
```
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
```
information/cli: Icinga application loader (version: r2.6.3-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: *******.*********
warning/ApplyRule: Apply rule 'satellite-host' (in /usr/local/etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /usr/local/etc/icinga2/conf.d/notifications.conf: 11:1-11:45) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /usr/local/etc/icinga2/conf.d/notifications.conf: 20:1-20:48) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'backup-downtime' (in /usr/local/etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 9 Endpoints.
information/ConfigItem: Instantiated 10 Zones.
information/ConfigItem: Instantiated 1 SyslogLogger.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 10747 Services.
information/ConfigItem: Instantiated 239 Comments.
information/ConfigItem: Instantiated 740 Dependencies.
information/ConfigItem: Instantiated 1236 Notifications.
information/ConfigItem: Instantiated 239 CheckCommands.
information/ConfigItem: Instantiated 4 ServiceGroups.
information/ConfigItem: Instantiated 5 TimePeriods.
information/ConfigItem: Instantiated 3 Users.
information/ConfigItem: Instantiated 2 UserGroups.
information/ConfigItem: Instantiated 1236 Hosts.
information/ConfigItem: Instantiated 21 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 3 NotificationCommands.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 GraphiteWriter.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 LivestatusListener.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```
* Single zone

**Comment by yoshi314** [comment]
I have the exact same problem when running the dashing dashboard for icinga2. After latest updates it works fine. but icinga crashed in the middle of the night so i had a several hour monitoring outage.

Same as in your case, no interesting logs.

This might be an easy to reproduce case.

**Comment by Crunsher** [comment]
I never had this problem when creating or querying objects.

icingaweb2 can use either external commands or the API to run 'check now', can you verify you are using the API as command transport?

**Comment by Stefar77** [comment]
Crunsher, the 'check now' is only a method to make it go down fast, it's the API call in the plugin that is killing my Icinga. My plugin updates Mitel Controller alerts (~10 passive) services and I had a but that ignored memcached and always pushed the status. (even when there was no change) when I change from socket to push passive checks to API in the poller the API will crash. 'Check Now' on 40 Mitel Controllers was 400 passive updates to the API and that kills it.

I fixed my poller and switched back to sockets to prevent the API from overloading until it's fixed. :-)

Ps. Normally Icinga has 46 threads and goes up and down to 46, when I stress the API it will stay at 128 threads and the API will hang until the Icinga process disappears a couple of hours later. 
This then also generates lots of timeouts in the Mitel pollers. 

Curl to the API port seems to hang forever and killall icinga also hangs. (only way to fix is the -KILL)

**Comment by Stefar77** [comment]
Just noticed;
curl -k -s -u login:pass -H 'Accept: application/json' -X POST 'https://localhost:5665/v1/events?queue=debugnotifications&types=Notification'

Creates a new thread that doesn't seem to end. (Not that I use events in my pollers but may be related in threads not always ending)

* still testing what causes it, if I query services 50 times in a row I don't notice any new threads.

**Comment by Stefar77** [comment]
Some threads backtraces while hanging...
``` -- 71
#0  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
#1  0x00000008047e2533 in _pthread_cond_wait () from /lib/libthr.so.3
#2  0x00000008022574d9 in boost::exception_detail::copy_boost_exception () from /usr/local/lib/icinga2/libbase.so.2.6.3
#3  0x0000000802236866 in icinga::Socket::~Socket () from /usr/local/lib/icinga2/libbase.so.2.6.3
#4  0x00000008021fca72 in icinga::Stream::WaitForData () from /usr/local/lib/icinga2/libbase.so.2.6.3
#5  0x0000000801b5b301 in icinga::ApiListener::NewClientHandlerInternal () from /usr/local/lib/icinga2/libremote.so.2.6.3
#6  0x0000000801b59d43 in icinga::ApiListener::NewClientHandler () from /usr/local/lib/icinga2/libremote.so.2.6.3
#7  0x00000008021e2075 in icinga::DynamicThreadPool::DoTasks () from /usr/local/lib/icinga2/libbase.so.2.6.3
#8  0x000000080084be94 in boost::thread::start_thread_noexcept () from /usr/local/lib/libboost_thread.so.1.64.0
#9  0x00000008047d6b55 in pthread_create () from /lib/libthr.so.3
```
``` 72
#0  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
#1  0x00000008047e2533 in _pthread_cond_wait () from /lib/libthr.so.3
#2  0x00000008022574d9 in boost::exception_detail::copy_boost_exception () from /usr/local/lib/icinga2/libbase.so.2.6.3
#3  0x0000000802236866 in icinga::Socket::~Socket () from /usr/local/lib/icinga2/libbase.so.2.6.3
#4  0x00000008021fca72 in icinga::Stream::WaitForData () from /usr/local/lib/icinga2/libbase.so.2.6.3
#5  0x0000000801b5b301 in icinga::ApiListener::NewClientHandlerInternal () from /usr/local/lib/icinga2/libremote.so.2.6.3
#6  0x0000000801b59d43 in icinga::ApiListener::NewClientHandler () from /usr/local/lib/icinga2/libremote.so.2.6.3
#7  0x00000008021e2075 in icinga::DynamicThreadPool::DoTasks () from /usr/local/lib/icinga2/libbase.so.2.6.3
#8  0x000000080084be94 in boost::thread::start_thread_noexcept () from /usr/local/lib/libboost_thread.so.1.64.0
#9  0x00000008047d6b55 in pthread_create () from /lib/libthr.so.3
```
``` 73
#0  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
#1  0x00000008047de41e in pthread_mutex_destroy () from /lib/libthr.so.3
#2  0x00000008047dd519 in pthread_mutex_lock () from /lib/libthr.so.3
#3  0x0000000801bde128 in boost::exception_detail::copy_boost_exception () from /usr/local/lib/icinga2/libremote.so.2.6.3
#4  0x0000000801b5ace7 in icinga::ApiListener::NewClientHandlerInternal () from /usr/local/lib/icinga2/libremote.so.2.6.3
#5  0x0000000801b59d43 in icinga::ApiListener::NewClientHandler () from /usr/local/lib/icinga2/libremote.so.2.6.3
#6  0x00000008021e2075 in icinga::DynamicThreadPool::DoTasks () from /usr/local/lib/icinga2/libbase.so.2.6.3
#7  0x000000080084be94 in boost::thread::start_thread_noexcept () from /usr/local/lib/libboost_thread.so.1.64.0
#8  0x00000008047d6b55 in pthread_create () from /lib/libthr.so.3
```
``` 74
#0  0x000000080450152a in _accept () from /lib/libc.so.7
#1  0x00000008047d9196 in pthread_suspend_all_np () from /lib/libthr.so.3
#2  0x00000008021f9f2c in icinga::Socket::Accept () from /usr/local/lib/icinga2/libbase.so.2.6.3
#3  0x0000000801b59a3b in icinga::ApiListener::ListenerThreadProc () from /usr/local/lib/icinga2/libremote.so.2.6.3
#4  0x0000000801c0d436 in boost::exception_detail::copy_boost_exception () from /usr/local/lib/icinga2/libremote.so.2.6.3
#5  0x000000080084be94 in boost::thread::start_thread_noexcept () from /usr/local/lib/libboost_thread.so.1.64.0
#6  0x00000008047d6b55 in pthread_create () from /lib/libthr.so.3
```
``` 75
#0  0x000000080451312a in _poll () from /lib/libc.so.7
#1  0x00000008047d95e6 in pthread_suspend_all_np () from /lib/libthr.so.3
#2  0x00000008021fa29d in icinga::Socket::Poll () from /usr/local/lib/icinga2/libbase.so.2.6.3
#3  0x0000000807a80295 in icinga::ObjectImpl<icinga::ExternalCommandListener>::ValidateCommandPath () from /usr/local/lib/icinga2/libcompat.so.2.6.3
#4  0x000000080084be94 in boost::thread::start_thread_noexcept () from /usr/local/lib/libboost_thread.so.1.64.0
#5  0x00000008047d6b55 in pthread_create () from /lib/libthr.so.3
```
``` 76
#0  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
#1  0x00000008047e2533 in _pthread_cond_wait () from /lib/libthr.so.3
#2  0x0000000807834af9 in boost::exception_detail::copy_boost_exception () from /usr/local/lib/icinga2/libchecker.so.2.6.3
#3  0x0000000807819b86 in icinga::ObjectImpl<icinga::CheckerComponent>::ValidateConcurrentChecks () from /usr/local/lib/icinga2/libchecker.so.2.6.3
#4  0x0000000807815be5 in icinga::ObjectImpl<icinga::CheckerComponent>::ValidateConcurrentChecks () from /usr/local/lib/icinga2/libchecker.so.2.6.3
#5  0x000000080084be94 in boost::thread::start_thread_noexcept () from /usr/local/lib/libboost_thread.so.1.64.0
#6  0x00000008047d6b55 in pthread_create () from /lib/libthr.so.3
```
``` 77
#0  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
#1  0x00000008047e2533 in _pthread_cond_wait () from /lib/libthr.so.3
#2  0x00000008022574d9 in boost::exception_detail::copy_boost_exception () from /usr/local/lib/icinga2/libbase.so.2.6.3
#3  0x0000000802236866 in icinga::Socket::~Socket () from /usr/local/lib/icinga2/libbase.so.2.6.3
#4  0x00000008022045fc in icinga::Timer::TimerThreadProc () from /usr/local/lib/icinga2/libbase.so.2.6.3
#5  0x000000080084be94 in boost::thread::start_thread_noexcept () from /usr/local/lib/libboost_thread.so.1.64.0
#6  0x00000008047d6b55 in pthread_create () from /lib/libthr.so.3
```

**Comment by Stefar77** [comment]
Here a list of threads after more testing, keeping gdb attached and pushing events until the thread count exceeded the limit (1500) and Icinga dies. But I'm pretty sure that's what eventually kills the Icinga2 process. Builds until the maximum threads and then the OS will kill it, I think I just missed the syslog message.

707 Threads, almost there..
```
55080 icinga      707  20    0   596M   326M nanslp  1   2:22   6.15% icinga2
```

```
* 83 Thread 805c18000 (LWP 102290/icinga2)  0x000000080450148a in _nanosleep () from /lib/libc.so.7
  82 Thread 80716e900 (LWP 101119/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  81 Thread 80716ee00 (LWP 101158/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  80 Thread 805c1b700 (LWP 102491/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  79 Thread 805c1b200 (LWP 102504/icinga2)  0x000000080451312a in _poll () from /lib/libc.so.7
  78 Thread 805c19e00 (LWP 102512/icinga2)  0x000000080450152a in _accept () from /lib/libc.so.7
  77 Thread 805c1a300 (LWP 102536/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  76 Thread 805c1a800 (LWP 102599/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  75 Thread 805c1ad00 (LWP 102635/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  74 Thread 80716f300 (LWP 102638/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  73 Thread 80716f800 (LWP 102681/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  72 Thread 80716fd00 (LWP 102860/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  71 Thread 807170200 (LWP 102880/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  70 Thread 807170700 (LWP 102940/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  69 Thread 807170c00 (LWP 102941/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  68 Thread 807171100 (LWP 102963/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  67 Thread 807171600 (LWP 103000/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  66 Thread 807171b00 (LWP 103078/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  65 Thread 80764c000 (LWP 103082/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  64 Thread 80764c500 (LWP 103131/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  63 Thread 80764ca00 (LWP 103184/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  62 Thread 80764cf00 (LWP 103320/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  61 Thread 80764d400 (LWP 103325/icinga2)  0x000000080451312a in _poll () from /lib/libc.so.7
  60 Thread 80764d900 (LWP 103336/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  59 Thread 80764de00 (LWP 103339/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  58 Thread 80764e300 (LWP 103343/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  57 Thread 80764e800 (LWP 103344/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  56 Thread 80764ed00 (LWP 103358/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  55 Thread 80764f200 (LWP 103380/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  54 Thread 80764f700 (LWP 103391/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  53 Thread 80764fc00 (LWP 103407/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  52 Thread 807650100 (LWP 103419/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  51 Thread 807650600 (LWP 103422/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  50 Thread 813458000 (LWP 103437/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  49 Thread 81325e000 (LWP 103449/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  48 Thread 813c5e500 (LWP 103469/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  47 Thread 813a5ea00 (LWP 103474/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  46 Thread 807650b00 (LWP 101354/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  45 Thread 806220000 (LWP 102124/icinga2)  0x000000080451312a in _poll () from /lib/libc.so.7
  44 Thread 806220500 (LWP 102193/icinga2)  0x000000080451312a in _poll () from /lib/libc.so.7
  43 Thread 806220a00 (LWP 102285/icinga2)  0x000000080451312a in _poll () from /lib/libc.so.7
  42 Thread 806220f00 (LWP 102568/icinga2)  0x000000080451312a in _poll () from /lib/libc.so.7
  41 Thread 81222ba00 (LWP 101349/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  40 Thread 80f983900 (LWP 103773/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  39 Thread 80f983e00 (LWP 101288/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  38 Thread 80f982a00 (LWP 103835/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  37 Thread 807176400 (LWP 102842/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  36 Thread 80f983400 (LWP 101709/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  35 Thread 805d97700 (LWP 100494/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  34 Thread 805d98b00 (LWP 100584/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  33 Thread 805d98600 (LWP 101028/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  32 Thread 805d98100 (LWP 101097/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  31 Thread 80716da00 (LWP 103288/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  30 Thread 807177d00 (LWP 103345/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  29 Thread 80716d500 (LWP 100527/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  28 Thread 807175500 (LWP 100587/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  27 Thread 807175a00 (LWP 103370/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  26 Thread 80f982000 (LWP 103420/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  25 Thread 807178700 (LWP 103430/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  24 Thread 807175f00 (LWP 100599/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  23 Thread 807175000 (LWP 100268/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  22 Thread 807176900 (LWP 100615/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  21 Thread 80f985200 (LWP 100637/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  20 Thread 807179b00 (LWP 100837/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  19 Thread 80f984800 (LWP 101106/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  18 Thread 807177800 (LWP 101131/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  17 Thread 80f984300 (LWP 101289/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  16 Thread 807179100 (LWP 101407/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  15 Thread 80f982500 (LWP 103455/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  14 Thread 80db6af00 (LWP 103859/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  13 Thread 80f982f00 (LWP 103860/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  12 Thread 807179600 (LWP 103861/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  11 Thread 811e2ce00 (LWP 103862/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  10 Thread 807178200 (LWP 103863/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  9 Thread 812a2e700 (LWP 103864/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  8 Thread 80dd8cf00 (LWP 103866/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  7 Thread 80e567900 (LWP 103867/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  6 Thread 807178c00 (LWP 103869/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  5 Thread 80f984d00 (LWP 101564/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  4 Thread 812032800 (LWP 103872/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  3 Thread 812031900 (LWP 101385/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  2 Thread 805d96d00 (LWP 103875/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
  1 Thread 812a2d300 (LWP 100650/icinga2)  0x00000008047e467c in pthread_cleanup_pop () from /lib/libthr.so.3
```

**Comment by Stefar77** [comment]
Deadlock while closing a connection somehow. (took me a while to get debugging enabled)
```
(gdb) thread 49
[Switching to thread 49 (Thread 807e5e400 (LWP 102880/icinga2))]#0  0x0000000804de567c in pthread_cleanup_pop () from /lib/libthr.so.3
(gdb) bt
#0  0x0000000804de567c in pthread_cleanup_pop () from /lib/libthr.so.3
#1  0x0000000804ddf41e in pthread_mutex_destroy () from /lib/libthr.so.3
#2  0x0000000804dde519 in pthread_mutex_lock () from /lib/libthr.so.3
#3  0x0000000801d01ea5 in boost::recursive_mutex::lock (this=0x80f15d2f0) at recursive_mutex.hpp:113
#4  0x0000000801d01deb in icinga::ObjectLock::LockMutex (object=0x80c416000) at objectlock.hpp:75
#5  0x0000000801d01d38 in icinga::ObjectLock::Lock (this=0x7fffd9dbb0d0) at objectlock.hpp:101
#6  0x0000000801cd8416 in icinga::ObjectLock::ObjectLock (this=0x7fffd9dbb0d0, object=0x80c416000) at objectlock.hpp:57
#7  0x0000000801c71de1 in icinga::ApiListener::RemoveHttpClient (this=0x80c416000, aclient=@0x7fffd9dbb150) at apilistener.cpp:1196
#8  0x0000000801ca68a4 in icinga::HttpServerConnection::Disconnect (this=0x813630a00) at httpserverconnection.cpp:81
#9  0x0000000801ca6737 in icinga::HttpServerConnection::DataAvailableHandler (this=0x813630a00) at httpserverconnection.cpp:226
```
```
[Switching to thread 48 (Thread 807e5e900 (LWP 102940/icinga2))]#0  0x0000000804de567c in pthread_cleanup_pop () from /lib/libthr.so.3
(gdb) bt
#0  0x0000000804de567c in pthread_cleanup_pop () from /lib/libthr.so.3
#1  0x0000000804ddf41e in pthread_mutex_destroy () from /lib/libthr.so.3
#2  0x0000000804dde519 in pthread_mutex_lock () from /lib/libthr.so.3
#3  0x0000000801d01ea5 in boost::recursive_mutex::lock (this=0x80f15d2f0) at recursive_mutex.hpp:113
#4  0x0000000801d01deb in icinga::ObjectLock::LockMutex (object=0x80c416000) at objectlock.hpp:75
#5  0x0000000801d01d38 in icinga::ObjectLock::Lock (this=0x7fffd9fbc0d0) at objectlock.hpp:101
#6  0x0000000801cd8416 in icinga::ObjectLock::ObjectLock (this=0x7fffd9fbc0d0, object=0x80c416000) at objectlock.hpp:57
#7  0x0000000801c71de1 in icinga::ApiListener::RemoveHttpClient (this=0x80c416000, aclient=@0x7fffd9fbc150) at apilistener.cpp:1196
#8  0x0000000801ca68a4 in icinga::HttpServerConnection::Disconnect (this=0x813830500) at httpserverconnection.cpp:81
#9  0x0000000801ca6737 in icinga::HttpServerConnection::DataAvailableHandler (this=0x813830500) at httpserverconnection.cpp:226
```

```
[Switching to thread 60 (Thread 80797ed00 (LWP 101958/icinga2))]#0  0x0000000804de567c in pthread_cleanup_pop () from /lib/libthr.so.3
(gdb) bt
#0  0x0000000804de567c in pthread_cleanup_pop () from /lib/libthr.so.3
#1  0x0000000804de3533 in _pthread_cond_wait () from /lib/libthr.so.3
#2  0x0000000802763a73 in boost::condition_variable::do_wait_until (this=0x812e21150, m=@0x7fffdb3d60e8, timeout=@0x7fffdb3d6048) at condition_variable.hpp:107
#3  0x00000008026f839c in boost::condition_variable::timed_wait (this=0x812e21150, m=@0x7fffdb3d60e8, abs_time=@0x7fffdb3d60d0) at condition_variable_fwd.hpp:142
#4  0x00000008026a99bd in icinga::SocketEventEngine::WakeUpThread (this=0x812e21000, sid=4, wait=true) at socketevents.cpp:73
#5  0x00000008026ab7d0 in icinga::SocketEventEnginePoll::Register (this=0x812e21000, se=0x813420f50, lifesupportObject=0x813420f00) at socketevents-poll.cpp:152
#6  0x00000008026a9ee8 in icinga::SocketEvents::Register (this=0x813420f50, lifesupportObject=0x813420f00) at socketevents.cpp:129
#7  0x00000008026a9eba in icinga::SocketEvents::SocketEvents (this=0x813420f50, socket=@0x812a17060, lifesupportObject=0x813420f00) at socketevents.cpp:119
#8  0x00000008026b4b70 in icinga::TlsStream::TlsStream (this=0x813420f00, socket=@0x812a17060, hostname=@0x812a17068, role=icinga::RoleServer, sslContext=@0x80c4161e0)
    at tlsstream.cpp:43
#9  0x0000000801c62ecb in icinga::ApiListener::NewClientHandlerInternal (this=0x80c416000, client=@0x812a17060, hostname=@0x812a17068, role=icinga::RoleServer)
    at apilistener.cpp:348
```

**Comment by Stefar77** [comment]
Hacked a solution!
Replaced the locks in ApiListener for the m_HttpClients with scoped locks seems to have solved it. 
It's sticking to 38 threads now and seems stable no matter how many passive I blast into the API.
