### ISSUE TITLE
The latest packages for RHEL/CentOS have a busted naming convention

### ISSUE THREAD

**Issue by farvour** [Icinga/icinga2#5455]
The RHEL/CentOS packages were built just fine prior to 2.7 with the right naming convention. Something broke this and now this breaks a lot of things that depend on including the version in package managers like yum. The chef icinga2 cookbook for example uses this platform as well.

https://packages.icinga.com/epel/7/release/x86_64/

```
  | icinga2-2.6.3-1.el7.centos.x86_64.rpm | 2017-03-29 10:38 | 9.0K
-- | -- | -- | --
  | icinga2-2.7.0-1.el7.icinga.x86_64.rpm | 2017-08-02 17:13 | 9.2K
```
It should be centos, not icinga

Example:
```  * yum_package[icinga2] action install
    
    ================================================================================
    Error executing action `install` on resource 'yum_package[icinga2]'
    ================================================================================
    
    Chef::Exceptions::Package
    -------------------------
    Version 2.7.0-1.el7.centos of icinga2 not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/icinga2/recipes/core_install.rb
    
     52:   package 'icinga2' do
     53:     version node['icinga2']['version'] + node['icinga2']['icinga2_version_suffix'] unless node['icinga2']['ignore_version']
     54:     notifies :restart, 'service[icinga2]', :delayed
     55:   end
     56: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/icinga2/recipes/core_install.rb:52:in `from_file'
    
    yum_package("icinga2") do
      package_name "icinga2"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "icinga2"
      recipe_name "core_install"
      version "2.7.0-1.el7.centos"
      flush_cache {:before=>false, :after=>false}
    end
    
    Platform:
    ---------
    x86_64-linux
```

It can be worked around by adjusting some attributes with the chef cookbook, but really, I don't understand why all of a sudden this would change un-necessarily?

**Comment by dnsmichi** [comment]
Open a new ticket in icinga/icinga-packaging please.

**Comment by lazyfrosch** [comment]
We rebuilt most of our build system to be able to ship reliable packages.

This includes minor but visible changes, like the suffix of package versions. Also vendor meta data in the RPM packages. Pretty much standard behavior.

Releases change stuff, I don't understand your problem here :cry:
