### ISSUE TITLE
2.7.1-1.wheezy segfaults

### ISSUE THREAD

**Issue by rgevaert** [Icinga/icinga2#5676]
I'm installing icinga2 on Debian wheezy and although many hosts worked out of the box I have one host that doesn't want to start icinga2.

## Expected Behavior

Icinga2 should start

## Current Behavior

```
[2017-10-13 15:25:29 +0200] information/ConfigItem: Committing config item(s).
[2017-10-13 15:25:29 +0200] notice/WorkQueue: Spawning WorkQueue threads for 'DaemonUtility::LoadConfigFiles'
[2017-10-13 15:25:29 +0200] information/ApiListener: My API identity: comes1.ugent.be
[2017-10-13 15:25:29 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2017-10-13 15:25:29 +0200] information/ConfigItem: Instantiated 4 Zones.
[2017-10-13 15:25:29 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2017-10-13 15:25:29 +0200] information/ConfigItem: Instantiated 2 Endpoints.
[2017-10-13 15:25:29 +0200] information/ConfigItem: Instantiated 202 CheckCommands.
[2017-10-13 15:25:29 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2017-10-13 15:25:29 +0200] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2017-10-13 15:25:29 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2017-10-13 15:25:29 +0200] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2017-10-13 15:25:29 +0200] notice/WorkQueue: Stopped WorkQueue threads for 'DaemonUtility::LoadConfigFiles'
[2017-10-13 15:25:29 +0200] notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/modified-attributes.conf
[2017-10-13 15:25:29 +0200] notice/WorkQueue: Spawning WorkQueue threads for 'DaemonCommand::Run'
[2017-10-13 15:25:29 +0200] information/ConfigItem: Triggering Start signal for config items
[2017-10-13 15:25:29 +0200] information/ApiListener: 'api' started.
Segmentation fault
```
GDB backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff0f6d700 (LWP 4371)]
0x00007ffff5a3541e in std::ostream::sentry::sentry(std::ostream&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff5a3541e in std::ostream::sentry::sentry(std::ostream&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff5a35b49 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff5a35f2f in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)
    () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff787b4af in icinga::StreamLogger::ProcessLogEntry(std::ostream&, icinga::LogEntry const&) () from /usr/lib/x86_64-linux-gnu/icinga2/libbase.so.2.7.1
#4  0x00007ffff787b7ef in icinga::IcingaLog(icinga::LogSeverity, icinga::String const&, icinga::String const&) () from /usr/lib/x86_64-linux-gnu/icinga2/libbase.so.2.7.1
#5  0x00007ffff1227874 in ?? () from /usr/lib/x86_64-linux-gnu/icinga2/libchecker.so.2.7.1
#6  0x00007ffff122633a in ?? () from /usr/lib/x86_64-linux-gnu/icinga2/libchecker.so.2.7.1
#7  0x00007ffff787a136 in icinga::ConfigObject::Activate(bool) () from /usr/lib/x86_64-linux-gnu/icinga2/libbase.so.2.7.1
#8  0x00007ffff7887b45 in icinga::WorkQueue::WorkerThreadProc() () from /usr/lib/x86_64-linux-gnu/icinga2/libbase.so.2.7.1
#9  0x00007ffff7fe3629 in ?? () from /usr/lib/libboost_thread.so.1.49.0
#10 0x00007ffff7bc7b50 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#11 0x00007ffff5254fbd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#12 0x0000000000000000 in ?? ()
```

## Context

Just installing icinga2 and getting it to talk to the master.

## Your Environment

* Version used (`icinga2 --version`):

~# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: 7 (wheezy)
  Kernel: Linux
  Kernel version: 3.2.0-4-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.7.2
  Build host: ad29d69d670c

* Operating System and version:

* Enabled features (`icinga2 feature list`):

~# icinga2 feature list
Disabled features: compatlog debuglog gelf graphite influxdb livestatus notification opentsdb perfdata statusdata syslog
Enabled features: api checker command mainlog

* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

This is an agent connectiong to a master.

**Comment by dnsmichi** [comment]
Mh can you install the debug packages and re-run that with gdb and generate a full backtrace please?

Instructions over here: https://www.icinga.com/docs/icinga2/latest/doc/21-development/#debug-requirements

**Comment by rgevaert** [comment]
Ah sorry for that. I didn't know and didn't look for such instructions.
(the boost pretty printer doesn't work, wheezy has python two, so I stayed on the master branch for that repo, but that doesn't help too)
```
~# gdb --args /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 daemon -x debug --no-stack-rlimit
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/root/.gdb_printers/Boost-Pretty-Printer/boost_print/__init__.py", line 41, in <module>
ImportError: No module named common
/root/.gdbinit:25: Error in sourced command file:
Error while executing Python code.
Reading symbols from /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2...Reading symbols from /usr/lib/debug/.build-id/46/6fd23b53c870e702c478fe7db6b3e7337a4a23.debug...done.
done.
(gdb) run
Starting program: /usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2 daemon -x debug --no-stack-rlimit
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3471700 (LWP 4929)]
[New Thread 0x7ffff2c70700 (LWP 4993)]
[New Thread 0x7ffff246f700 (LWP 4996)]
[New Thread 0x7ffff1c6e700 (LWP 4998)]
[New Thread 0x7ffff146d700 (LWP 5000)]
[New Thread 0x7ffff0c6c700 (LWP 5001)]
[2017-10-13 16:01:21 +0200] information/cli: Icinga application loader (version: r2.7.1-1)
[2017-10-13 16:01:21 +0200] information/cli: Loading configuration file(s).
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /etc/icinga2/icinga2.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /etc/icinga2/constants.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /etc/icinga2/zones.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/itl
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command-icinga.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/nscp
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command-nscp-local.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command-plugins.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/databases.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/hardware.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/icingacli.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/ipmi.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/logmanagement.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/metrics.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/network-components.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/network-services.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/operating-system.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/raid-controller.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/smart-attributes.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/storage.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/virtualization.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/vmware.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/plugins-contrib.d/web.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/windows-plugins
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /usr/share/icinga2/include/command-plugins-windows.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/api.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/checker.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/command.conf
[2017-10-13 16:01:21 +0200] notice/ConfigCompiler: Compiling config file: /etc/icinga2/features-enabled/mainlog.conf
[2017-10-13 16:01:21 +0200] notice/Loader: Loading library 'libchecker.so.2.7.1'
[2017-10-13 16:01:22 +0200] notice/Loader: Loading library 'libcompat.so.2.7.1'
[2017-10-13 16:01:22 +0200] information/ConfigItem: Committing config item(s).
[2017-10-13 16:01:22 +0200] notice/WorkQueue: Spawning WorkQueue threads for 'DaemonUtility::LoadConfigFiles'
[New Thread 0x7fffe9f81700 (LWP 5026)]
[New Thread 0x7fffe9780700 (LWP 5027)]
[New Thread 0x7fffe8f7f700 (LWP 5028)]
[New Thread 0x7fffe877e700 (LWP 5029)]
[New Thread 0x7fffe7f7d700 (LWP 5030)]
[New Thread 0x7fffe777c700 (LWP 5031)]
[New Thread 0x7fffe6f7b700 (LWP 5032)]
[New Thread 0x7fffe677a700 (LWP 5033)]
[2017-10-13 16:01:22 +0200] information/ApiListener: My API identity: comes1.ugent.be
[2017-10-13 16:01:22 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2017-10-13 16:01:22 +0200] information/ConfigItem: Instantiated 4 Zones.
[2017-10-13 16:01:22 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2017-10-13 16:01:22 +0200] information/ConfigItem: Instantiated 2 Endpoints.
[2017-10-13 16:01:22 +0200] information/ConfigItem: Instantiated 202 CheckCommands.
[2017-10-13 16:01:22 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2017-10-13 16:01:22 +0200] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2017-10-13 16:01:22 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2017-10-13 16:01:22 +0200] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[Thread 0x7fffe9780700 (LWP 5027) exited]
[Thread 0x7fffe6f7b700 (LWP 5032) exited]
[Thread 0x7fffe877e700 (LWP 5029) exited]
[Thread 0x7fffe8f7f700 (LWP 5028) exited]
[Thread 0x7fffe7f7d700 (LWP 5030) exited]
[Thread 0x7fffe777c700 (LWP 5031) exited]
[Thread 0x7fffe9f81700 (LWP 5026) exited]
[2017-10-13 16:01:22 +0200] notice/WorkQueue: Stopped WorkQueue threads for 'DaemonUtility::LoadConfigFiles'
[2017-10-13 16:01:22 +0200] notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/modified-attributes.conf
[2017-10-13 16:01:22 +0200] notice/WorkQueue: Spawning WorkQueue threads for 'DaemonCommand::Run'
[Thread 0x7fffe677a700 (LWP 5033) exited]
[New Thread 0x7fffe677a700 (LWP 5034)]
[New Thread 0x7fffe6f7b700 (LWP 5035)]
[New Thread 0x7fffe777c700 (LWP 5036)]
[New Thread 0x7fffe7f7d700 (LWP 5039)]
[New Thread 0x7fffe9f81700 (LWP 5040)]
[New Thread 0x7fffe9780700 (LWP 5041)]
[New Thread 0x7fffe8f7f700 (LWP 5042)]
[New Thread 0x7fffe877e700 (LWP 5043)]
[2017-10-13 16:01:22 +0200] information/ConfigItem: Triggering Start signal for config items
[2017-10-13 16:01:22 +0200] information/ApiListener: 'api' started.
[2017-10-13 16:01:22 +0200] information/ApiListener: Adding new listener on port '5665'
[New Thread 0x7fffe5f79700 (LWP 5044)]
[New Thread 0x7fffe5778700 (LWP 5045)]
[2017-10-13 16:01:22 +0200] debug/ApiListener: Not connecting to Endpoint 'comes1.ugent.be' because that's us.
[2017-10-13 16:01:22 +0200] notice/ApiListener: Current zone master: comes1.ugent.be
[2017-10-13 16:01:22 +0200] notice/ApiListener: Connected endpoints: 

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe5778700 (LWP 5045)]
0x00007ffff5a3541e in std::ostream::sentry::sentry(std::ostream&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff5a3541e in std::ostream::sentry::sentry(std::ostream&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff5a35b49 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff5a35f2f in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)
    () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff787b4af in icinga::StreamLogger::ProcessLogEntry (stream=..., entry=...)
    at /home/jenkins/workspace/icinga2-release/deb-debian-wheezy-1binary/arch/x86_64/icinga2/lib/base/streamlogger.cpp:101
#4  0x00007ffff787b7ef in icinga::IcingaLog (severity=<optimized out>, facility=..., message=...)
    at /home/jenkins/workspace/icinga2-release/deb-debian-wheezy-1binary/arch/x86_64/icinga2/lib/base/logger.cpp:109
#5  0x00007ffff6feb204 in icinga::Log::~Log (this=0x7fffe57778a0, __in_chrg=<optimized out>)
    at /home/jenkins/workspace/icinga2-release/deb-debian-wheezy-1binary/arch/x86_64/icinga2/lib/base/logger.hpp:124
#6  0x00007ffff6fdf68c in icinga::ApiListener::AddConnection (this=0x6386b0, endpoint=...)
    at /home/jenkins/workspace/icinga2-release/deb-debian-wheezy-1binary/arch/x86_64/icinga2/lib/remote/apilistener.cpp:297
#7  0x00007ffff7fe3629 in ?? () from /usr/lib/libboost_thread.so.1.49.0
#8  0x00007ffff7bc7b50 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007ffff5254fbd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x0000000000000000 in ?? ()
```
btw it's very nice to have those instructions on the site!

**Comment by dnsmichi** [comment]
You can ignore the boost pretty printer, that chapter is a mix of user and developer docs and needs enhancements (i.e. a user report chapter, and then an enhanced build and debug chapter). It is still a good place to hand over to users experiencing crashes.

I cannot really see why Icinga 2 would crash here while logging something during the ApiListener Reconnect timer. 

Can you re-run this with a full backtrace please?
https://www.icinga.com/docs/icinga2/latest/doc/21-development/#gdb-backtrace

**Comment by rgevaert** [comment]
http://users.ugent.be/~rgevaert/gdb.txt.gz

**Comment by dnsmichi** [comment]
[gdb.txt.gz](https://github.com/Icinga/icinga2/files/1386913/gdb.txt.gz)

Seems it crashes right here. That's weird.

```
        Log(LogInformation, "ApiListener")
            << "Adding new listener on port '" << service << "'";
```

**Comment by rgevaert** [comment]
The problem has resolved it selves. I have no idea why...

**Comment by dnsmichi** [comment]
Thanks for the update 👍
