### ISSUE TITLE
icinga segfault error running on CentOS 7.4

### ISSUE THREAD

**Issue by silenceJI** [Icinga/icinga2#5978]
## Expected Behavior

icinga abnormal exit, message log:

```
Jan 15 14:24:52 l-qicingam1.ops.cn2 kernel: icinga2[24989]: segfault at 10 ip 00007fd0e9b3abf0 sp 00007fd0ce0e2a58 error 6
Jan 15 14:24:52 l-qicingam1.ops.cn2 kernel: icinga2[24991]: segfault at 18 ip 00007fd0e83097d0 sp 00007fd0ce060a28 error 4
Jan 15 14:24:52 l-qicingam1.ops.cn2 kernel: in libstdc++.so.6.0.19[7fd0e8294000+e9000]
Jan 15 14:24:52 l-qicingam1.ops.cn2 kernel:
Jan 15 14:24:52 l-qicingam1.ops.cn2 kernel: in libremote.so.2.8.0[7fd0e9ae9000+153000]
Jan 15 14:24:52 l-qicingam1.ops.cn2 kernel:
Jan 15 14:24:52 l-qicingam1.ops.cn2 systemd: icinga2.service: main process exited, code=killed, status=11/SEGV
Jan 15 14:24:52 l-qicingam1.ops.cn2 systemd: Unit icinga2.service entered failed state.
```

## Current Behavior

Same as above

## Possible Solution

NO

The system is downgraded to CentOS 7.3, retry;

## Steps to Reproduce (for bugs)

1.Build icinga cluster;
2.Use the API to add monitoring data
3.
4.

## Your Environment

* Version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.11.6.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
```

* Operating System and version:
```
cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
```

* Enabled features (`icinga2 feature list`):
```
icinga2 feature list
Disabled features: command compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker ido-mysql mainlog notification
```

* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
```
icinga2 daemon -C
information/cli: Icinga application loader (version: r2.8.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
warning/Zone: The Zone object 'zone-cn2' has more than two endpoints. Due to a known issue this type of configuration is strongly discouraged and may cause Icinga to use excessive amounts of CPU time.
information/ApiListener: My API identity: l-qicingam1.ops.cn2
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 4 Zones.
information/ConfigItem: Instantiated 5 Endpoints.
information/ConfigItem: Instantiated 7 ApiUsers.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 4 NotificationCommands.
information/ConfigItem: Instantiated 3939 Notifications.
information/ConfigItem: Instantiated 424 CheckCommands.
information/ConfigItem: Instantiated 1 EventCommand.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 254 Hosts.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 9652 Users.
information/ConfigItem: Instantiated 2 ServiceGroups.
information/ConfigItem: Instantiated 3250 Services.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
```
object Endpoint "l-qicingam1.ops.cn2" {
        host = "10.90.0.35"
//      log_duration = 5m
}

object Endpoint "l-qicingam2.ops.cn2" {
        host = "10.90.0.44"
//      log_duration = 5m
}

object Endpoint "l-qicingan1.ops.cn2" {
        host = "10.90.0.104"
        log_duration = 0
}

object Endpoint "l-qicingan2.ops.cn2" {
        host = "10.90.0.105"
        log_duration = 0
}

object Endpoint "l-qicingan3.ops.cn2" {
        host = "10.90.0.106"
        log_duration = 0
}

object Zone "master" {
        endpoints = [ "l-qicingam1.ops.cn2", "l-qicingam2.ops.cn2" ]
}

object Zone "zone-cn2" {
        endpoints = [ "l-qicingan1.ops.cn2", "l-qicingan2.ops.cn2","l-qicingan3.ops.cn2" ]
        parent = "master"
}

/* sync global commands */
object Zone "global-templates" {
        global = true
}

object Zone "director-global" {
        global = true
}
```

**Comment by gunnarbeutner** [comment]
Please provide information about how to reproduce this problem.

**Comment by silenceJI** [comment]
1.Build icinga cluster;
2.Use the API to add monitoring data;
3.Icinga process to exit;

Not accidental, it is inevitable.

Do you still need any information?

**Comment by gunnarbeutner** [comment]
Given the level of detail of your description (or rather, lack thereof) I'm unable to reproduce the problem here.

**Comment by dnsmichi** [comment]
Please show us which commands you're firing, the output and a step-by-step guide how to reliably reproduce the error.

Cheers,
Michael

**Comment by silenceJI** [comment]
This cluster is a new cluster, we are using the API to import monitoring data, the icinga process to exit? The following is part of the debug log:

ICINGA log:
```
[2018-01-16 15:36:21 +0800] information/HttpServerConnection: Request: GET /v1/objects/services/l-hdps215.data.cn2%21check_ping?attrs=__name (from [100.80.136.130]:51790, user: watcherapi)
[2018-01-16 15:36:21 +0800] notice/JsonRpcConnection: Received 'event::SetNextCheck' message from 'l-qicingan1.ops.cn2'
[2018-01-16 15:36:21 +0800] notice/JsonRpcConnection: Received 'event::SetNextCheck' message from 'l-qicingan1.ops.cn2'
[2018-01-16 15:36:21 +0800] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-01-16 15:36:21 +0800] notice/ApiListener: Sending message 'event::SetNextCheck' to 'l-qicingam2.ops.cn2'
[2018-01-16 15:36:21 +0800] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-01-16 15:36:21 +0800] notice/ApiListener: Sending message 'event::SetNextCheck' to 'l-qicingam2.ops.cn2'
[2018-01-16 15:36:21 +0800] notice/JsonRpcConnection: Received 'event::CheckResult' message from 'l-qicingan1.ops.cn2'
[2018-01-16 15:36:21 +0800] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-01-16 15:36:21 +0800] notice/ApiListener: Sending message 'event::SetNextCheck' to 'l-qicingam2.ops.cn2'
[2018-01-16 15:36:21 +0800] debug/DbEvents: add checkable check history for 'l-oaapp1.ops.cn2!check_qflume'
[2018-01-16 15:36:21 +0800] notice/ApiListener: Relaying 'event::CheckResult' message
[2018-01-16 15:36:21 +0800] notice/ApiListener: Sending message 'event::CheckResult' to 'l-qicingam2.ops.cn2'
[2018-01-16 15:36:21 +0800] warning/TlsStream: TLS stream was disconnected.
[2018-01-16 15:36:21 +0800] debug/HttpServerConnection: Http client disconnected
[2018-01-16 15:36:21 +0800] notice/WorkQueue: Stopped WorkQueue threads for 'HttpServerConnection'
[2018-01-16 15:36:21 +0800] notice/JsonRpcConnection: Received 'event::SetNextCheck' message from 'l-qicingan1.ops.cn2'
[2018-01-16 15:36:21 +0800] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-01-16 15:36:21 +0800] notice/ApiListener: Sending message 'event::SetNextCheck' to 'l-qicingam2.ops.cn2'
[2018-01-16 15:36:21 +0800] notice/JsonRpcConnection: Received 'event::CheckResult' message from 'l-qicingan1.ops.cn2'
[2018-01-16 15:36:21 +0800] information/ApiListener: New client connection from [100.80.136.130]:51791 (no client certificate)
[2018-01-16 15:36:21 +0800] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-01-16 15:36:21 +0800] notice/ApiListener: Sending message 'event::SetNextCheck' to 'l-qicingam2.ops.cn2'
[2018-01-16 15:36:21 +0800] debug/DbEvents: add checkable check history for 'l-hpb18.h.cn2!check_ping'
[2018-01-16 15:36:21 +0800] notice/ApiListener: Relaying 'event::CheckResult' message
[2018-01-16 15:36:21 +0800] notice/ApiListener: Sending message 'event::CheckResult' to 'l-qicingam2.ops.cn2'
[2018-01-16 15:36:21 +0800] notice/ApiListener: New HTTP client
[2018-01-16 15:36:21 +0800] debug/HttpRequest: line: GET /v1/objects/hosts/l-esaaslave6.ops.cn2?attrs=__name HTTP/1.1, tokens: 3
[2018-01-16 15:36:21 +0800] notice/WorkQueue: Spawning WorkQueue threads for 'HttpServerConnection'
[2018-01-16 15:36:21 +0800] information/HttpServerConnection: Request: GET /v1/objects/hosts/l-esaaslave6.ops.cn2?attrs=__name (from [100.80.136.130]:51791, user: watcherapi)
[2018-01-16 15:36:21 +0800] warning/TlsStream: TLS stream was disconnected.
[2018-01-16 15:36:21 +0800] debug/HttpServerConnection: Http client disconnected
[2018-01-16 15:36:21 +0800] notice/WorkQueue: Stopped WorkQueue threads for 'HttpServerConnection'
[2018-01-16 15:36:22 +0800] notice/JsonRpcConnection: Received 'event::SetNextCheck' message from 'l-qicingan1.ops.cn2'
[2018-01-16 15:36:22 +0800] notice/ApiListener: Relaying 'event::SetNextCheck' message
[2018-01-16 15:36:22 +0800] notice/ApiListener: Sending message 'event::SetNextCheck' to 'l-qicingam2.ops.cn2'
[2018-01-16 15:36:22 +0800] information/ApiListener: New client connection from [100.80.136.130]:51792 (no client certificate)
[2018-01-16 15:36:22 +0800] notice/ApiListener: New HTTP client
[2018-01-16 15:36:22 +0800] debug/HttpRequest: line: PUT /v1/objects/notifications/l-hdps803.data.cn2!check_disk!push-notification HTTP/1.1, tokens: 3
[2018-01-16 15:36:22 +0800] notice/WorkQueue: Spawning WorkQueue threads for 'HttpServerConnection'
[2018-01-16 15:36:22 +0800] information/HttpServerConnection: Request: PUT /v1/objects/notifications/l-hdps803.data.cn2%21check_disk%21push-notification (from [100.80.136.130]:51792, user: watcherapi)
[2018-01-16 15:36:22 +0800] notice/ConfigCompiler: Compiling config file: /var/lib/icinga2/api/packages/_api/l-qicingam1.ops.cn2-1516086486-0/conf.d/notifications/l-hdps803.data.cn2!check_disk!push-notification.conf
[2018-01-16 15:36:22 +0800] information/ConfigItem: Committing config item(s).
[2018-01-16 15:36:22 +0800] notice/WorkQueue: Spawning WorkQueue threads for ''
[2018-01-16 15:36:22 +0800] information/ConfigItem: Instantiated 1 Notification.
[2018-01-16 15:36:22 +0800] information/ConfigItem: Triggering Start signal for config items
[2018-01-16 15:36:22 +0800] information/ConfigItem: Activated all objects.
[2018-01-16 15:36:22 +0800] notice/ApiListener: Relaying 'config::UpdateObject' message
[2018-01-16 15:36:22 +0800] notice/ApiListener: Sending message 'config::UpdateObject' to 'l-qicingam2.ops.cn2'
[2018-01-16 15:36:22 +0800] information/ApiListener: New client connection from [100.80.136.130]:51793 (no client certificate)
[2018-01-16 15:36:22 +0800] notice/ApiListener: New HTTP client
[2018-01-16 15:36:22 +0800] debug/HttpRequest: line: PUT /v1/objects/services/l-esaaslave6.ops.cn2!procs_syslogd HTTP/1.1, tokens: 3
```

message log:
```
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Finished reconnecting to endpoint 'l-qicingan1.ops.cn2' via host '10.90.0.104' and port '5665'
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: New client connection for identity 'l-qicingam2.ops.cn2' to [10.90.0.44]:5665
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Sending config updates for endpoint 'l-qicingan1.ops.cn2' in zone 'zone-cn2'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Syncing configuration files for global zone 'global-templates' to endpoint 'l-qicingan1.ops.cn2'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Finished reconnecting to endpoint 'l-qicingam2.ops.cn2' via host '10.90.0.44' and port '5665'
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Sending config updates for endpoint 'l-qicingam2.ops.cn2' in zone 'master'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Syncing configuration files for global zone 'global-templates' to endpoint 'l-qicingam2.ops.cn2'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: New client connection for identity 'l-qicingan2.ops.cn2' to [10.90.0.105]:5665
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Finished reconnecting to endpoint 'l-qicingan2.ops.cn2' via host '10.90.0.105' and port '5665'
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Sending config updates for endpoint 'l-qicingan2.ops.cn2' in zone 'zone-cn2'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Syncing configuration files for global zone 'global-templates' to endpoint 'l-qicingan2.ops.cn2'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/JsonRpcConnection: Received certificate request for CN 'l-qicingan2.ops.cn2' signed by our CA.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/JsonRpcConnection: The certificate for CN 'l-qicingan2.ops.cn2' cannot be renewed yet.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Finished sending config file updates for endpoint 'l-qicingan1.ops.cn2' in zone 'zone-cn2'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Syncing runtime objects to endpoint 'l-qicingan1.ops.cn2'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: New client connection for identity 'l-qicingan3.ops.cn2' to [10.90.0.106]:5665
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Finished sending config file updates for endpoint 'l-qicingam2.ops.cn2' in zone 'master'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Syncing runtime objects to endpoint 'l-qicingam2.ops.cn2'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Finished reconnecting to endpoint 'l-qicingan3.ops.cn2' via host '10.90.0.106' and port '5665'
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Sending config updates for endpoint 'l-qicingan3.ops.cn2' in zone 'zone-cn2'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Syncing configuration files for global zone 'global-templates' to endpoint 'l-qicingan3.ops.cn2'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Finished sending config file updates for endpoint 'l-qicingan2.ops.cn2' in zone 'zone-cn2'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Syncing runtime objects to endpoint 'l-qicingan2.ops.cn2'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/JsonRpcConnection: Received certificate request for CN 'l-qicingan3.ops.cn2' signed by our CA.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/JsonRpcConnection: The certificate for CN 'l-qicingan3.ops.cn2' cannot be renewed yet.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] warning/ApiListener: Ignoring config update. 'api' does not accept config.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Finished sending config file updates for endpoint 'l-qicingan3.ops.cn2' in zone 'zone-cn2'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/ApiListener: Syncing runtime objects to endpoint 'l-qicingan3.ops.cn2'.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/NotificationComponent: 'notification' started.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/DbConnection: 'ido-mysql' started.
Jan 16 15:35:07 l-qicingam1.ops.cn2 icinga2: [2018-01-16 15:35:07 +0800] information/CheckerComponent: 'checker' started.
Jan 16 15:35:08 l-qicingam1.ops.cn2 systemd: Started Icinga host/service/network monitoring system.
Jan 16 15:36:22 l-qicingam1.ops.cn2 kernel: icinga2[5314]: segfault at 23 ip 00007f050b52cb42 sp 00007f05044709e0 error 4
Jan 16 15:36:22 l-qicingam1.ops.cn2 kernel: icinga2[705]: segfault at 23 ip 00007f050b543349 sp 00007f04ffb36a60 error 4
Jan 16 15:36:22 l-qicingam1.ops.cn2 kernel: in libremote.so.2.8.0[7f050b497000+153000]
Jan 16 15:36:22 l-qicingam1.ops.cn2 kernel:
Jan 16 15:36:22 l-qicingam1.ops.cn2 kernel: in libremote.so.2.8.0[7f050b497000+153000]
Jan 16 15:36:22 l-qicingam1.ops.cn2 kernel:
Jan 16 15:36:22 l-qicingam1.ops.cn2 systemd: icinga2.service: main process exited, code=killed, status=11/SEGV
Jan 16 15:36:22 l-qicingam1.ops.cn2 systemd: Unit icinga2.service entered failed state.
Jan 16 15:36:22 l-qicingam1.ops.cn2 systemd: icinga2.service failed.

```

And now found a problem. CentOS7.3 also have this problem, it is unclear whether the icinga version result?

In addition, I am not a developer, so the code debugging ability is relatively weak; if I need to operate what, please describe some clearly;

**Comment by dnsmichi** [comment]
I'd like to see the full gdb backtrace this crash generates, please. A yet more detailed description for getting such is here: 

https://www.icinga.com/docs/icinga2/latest/doc/21-development/#debug-requirements
https://www.icinga.com/docs/icinga2/latest/doc/21-development/#gdb-backtrace

**Comment by silenceJI** [comment]
thanks you,

We try to use GDB to run ICINGA2, but found that ICINGA is slow to run, API requests are 32 concurrency, 1 second can only add 2 to 3 monitoring items, Finally, this problem has emerged;

```
[2018-01-16 18:56:43 +0800] information/HttpServerConnection: Request: PUT /v1/objects/notifications/l-qfare35.f.cn2%21check_qflume%21mail-notification (from [10.86.214.129]:43277,
user: watcherapi)
[2018-01-16 18:56:43 +0800] information/ConfigItem: Committing config item(s).
[Thread 0x7fffd0ff9700 (LWP 25644) exited]
[New Thread 0x7fff937fe700 (LWP 25653)]
[New Thread 0x7fffd0ff9700 (LWP 25654)]
[2018-01-16 18:56:43 +0800] information/ConfigItem: Instantiated 1 Notification.
[2018-01-16 18:56:43 +0800] information/ConfigItem: Triggering Start signal for config items
[2018-01-16 18:56:43 +0800] information/ConfigItem: Activated all objects.
[2018-01-16 18:56:43 +0800] information/ApiListener: New client connection from [10.86.214.129]:43278 (no client certificate)

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff357fa700 (LWP 20829)]
icinga::intrusive_ptr_release(icinga::Object*) [clone .local.3782] (object=0x1) at /usr/src/debug/icinga2-2.8.0/lib/base/object.hpp:195
195             if (unlikely(refs == 0)) {
Missing separate debuginfos, use: debuginfo-install boost-program-options-1.53.0-26.el7.x86_64 boost-regex-1.53.0-26.el7.x86_64 boost-system-1.53.0-26.el7.x86_64 boost-thread-1.53.0
-26.el7.x86_64 glibc-2.17-157.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.14.1-26.el7.x86_64 libcom_err-1.42.9-9.el7.x86_64 libedit-3.0-12.20121213cvs.el7.x86_64 libgcc-
4.8.5-11.el7.x86_64 libicu-50.1.2-15.el7.x86_64 libselinux-2.5-6.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 mariadb-libs-5.5.52-1.el7.x86_64 ncurses-libs-5.9-13.20130511.el7.x86_64 op
enssl-libs-1.0.1e-60.el7.x86_64 pcre-8.32-15.el7_2.1.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  icinga::intrusive_ptr_release(icinga::Object*) [clone .local.3782] (object=0x1) at /usr/src/debug/icinga2-2.8.0/lib/base/object.hpp:195
#1  0x00007ffff68ce3a2 in __base_dtor (this=<optimized out>) at /usr/include/boost/smart_ptr/intrusive_ptr.hpp:97
#2  __base_dtor (this=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_tree.h:131
#3  destroy (this=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.8.2/ext/new_allocator.h:124
#4  std::_Rb_tree<boost::intrusive_ptr<icinga::HttpServerConnection>, boost::intrusive_ptr<icinga::HttpServerConnection>, std::_Identity<boost::intrusive_ptr<icinga::HttpServerConne
ction> >, std::less<boost::intrusive_ptr<icinga::HttpServerConnection> >, std::allocator<boost::intrusive_ptr<icinga::HttpServerConnection> > >::_M_destroy_node(std::_Rb_tree_node<boost::intrusive_ptr<icinga::HttpServerConnection> >*) [clone .isra.794] (
    __p=0x7fff6c000de8) at /usr/include/c++/4.8.2/bits/stl_tree.h:421
#5  _M_erase_aux (__position=..., this=0x7fff6c000de0) at /usr/include/c++/4.8.2/bits/stl_tree.h:1746
#6  erase (this=<optimized out>, __position=...) at /usr/include/c++/4.8.2/bits/stl_tree.h:809
#7  _M_erase_aux (__last=..., __first=..., this=0x7fff6c000de0) at /usr/include/c++/4.8.2/bits/stl_tree.h:1760
#8  erase (this=<optimized out>, __first=..., __last=...) at /usr/include/c++/4.8.2/bits/stl_tree.h:842
#9  erase (__x=..., this=0x7fff6c000de0) at /usr/include/c++/4.8.2/bits/stl_tree.h:1771
#10 erase (this=0x7fff6c000de0, __x=...) at /usr/include/c++/4.8.2/bits/stl_set.h:582
#11 icinga::ApiListener::RemoveHttpClient (this=0x7fff6c000c20, aclient=...) at /usr/src/debug/icinga2-2.8.0/lib/remote/apilistener.cpp:1382
#12 0x00007ffff68d2d48 in icinga::HttpServerConnection::Disconnect (this=this@entry=0x7ffed40babc0)
    at /usr/src/debug/icinga2-2.8.0/lib/remote/httpserverconnection.cpp:82
#13 0x00007ffff68d926a in icinga::HttpServerConnection::DataAvailableHandler (this=0x7ffed40babc0)
    at /usr/src/debug/icinga2-2.8.0/lib/remote/httpserverconnection.cpp:289
#14 0x00007ffff716e273 in operator() (a0=..., this=<optimized out>) at /usr/include/boost/function/function_template.hpp:767
#15 m_invoke (this=<optimized out>, func=..., args=...) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:89
#16 operator() (this=<optimized out>, func=..., args=...) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:78
#17 m_invoke (this=<optimized out>, connectionBody=...) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:114
#18 operator() (this=<optimized out>, connectionBody=...) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:107
#19 dereference (this=0x7fff357e8f10) at /usr/include/boost/signals2/detail/slot_call_iterator.hpp:82
#20 dereference (f=...) at /usr/include/boost/iterator/iterator_facade.hpp:514
#21 operator* (this=<optimized out>) at /usr/include/boost/iterator/iterator_facade.hpp:639
#22 operator() (last=..., first=..., this=<optimized out>) at /usr/include/boost/signals2/optional_last_value.hpp:55
#23 operator() (this=<optimized out>, combiner=..., first=..., last=...) at /usr/include/boost/signals2/detail/result_type_wrapper.hpp:64
#24 boost::signals2::detail::signal_impl<void (boost::intrusive_ptr<icinga::Stream> const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (b
oost::intrusive_ptr<icinga::Stream> const&)>, boost::function<void (boost::signals2::connection const&, boost::intrusive_ptr<icinga::Stream> const&)>, boost::signals2::mutex>::opera
tor()(boost::intrusive_ptr<icinga::Stream> const&) [clone .local.370] (
    this=0x7ffed40b2180, args#0=...) at /usr/include/boost/signals2/detail/signal_template.hpp:246
---Type <return> to continue, or q <return> to quit---
#25 0x00007ffff71affb7 in operator() (this=0x7ffed40b45a8, args#0=...) at /usr/include/boost/signals2/detail/signal_template.hpp:695
#26 icinga::Stream::SignalDataAvailable (this=0x7ffed40b4590) at /usr/src/debug/icinga2-2.8.0/lib/base/stream.cpp:55
#27 0x00007ffff71b017d in icinga::TlsStream::CloseInternal (this=0x7ffed40b4590, inDestructor=<optimized out>)
    at /usr/src/debug/icinga2-2.8.0/lib/base/tlsstream.cpp:358
#28 0x00007ffff71b064c in icinga::TlsStream::OnEvent (this=0x7ffed40b4590, revents=<optimized out>)
    at /usr/src/debug/icinga2-2.8.0/lib/base/tlsstream.cpp:243
#29 0x00007ffff71d9753 in icinga::SocketEventEngineEpoll::ThreadProc(int) (this=0x7fff3c000e60, tid=3)
    at /usr/src/debug/icinga2-2.8.0/lib/base/socketevents-epoll.cpp:125
#30 0x00007ffff7bd327a in thread_proxy () from /lib64/libboost_thread-mt.so.1.53.0
#31 0x00007ffff491adc5 in start_thread () from /lib64/libpthread.so.0
#32 0x00007ffff464973d in clone () from /lib64/libc.so.6

```

**Comment by dnsmichi** [comment]
Thanks. I'd say this is the same as #5807, @gunnarbeutner ? :)

**Comment by silenceJI** [comment]
Hello, we first spoke icinga2 upgrade to 2.8.1 version, after a day of testing, add 150,000 consecutive monitoring items, with notification items, about 300,000 objects, there is no above problem, thank you！

**Comment by silenceJI** [comment]
You can close this issus, thanks again!
