### ISSUE TITLE
Icinga 2.8.4 sometimes crashes at startup with segfault after installing openssl-libs-1.0.2k-12.el7.x86_64

### ISSUE THREAD

**Issue by bardahlm** [Icinga/icinga2#6358]
## Current Behavior

Icinga sometimes crashes at startup with segfault:

```
2018-06-08T08:05:48.148586+02:00 host=icingamaster1 pid=- process=kernel facility=kern severity=info icinga2[3084]: segfault at 7f67004c9000 ip 00007f670007ad5a sp 00007f66f8d5ab80 error 4 in libcrypto.so.1.0.2k[7f6700001000+234000]
```

## Possible Solution

Workaround: downgrade to openssl-libs-1.0.2k-8.el7.x86_64

## Steps to Reproduce (for bugs)

1. Upgrade to openssl-libs-1.0.2k-12.el7.x86_64
2. set up Icinga2 master node (crash do not happen on my satellite servers)
3. run gdb --args /usr/lib64/icinga2/sbin/icinga2 daemon -C  --no-stack-rlimit
4. start the program using r, repeat untill crash
5. Note logs:
```
(gdb) r
Starting program: /usr/lib64/icinga2/sbin/icinga2 daemon -C
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff0f3d700 (LWP 13033)]
[New Thread 0x7fffe873c700 (LWP 13034)]
[New Thread 0x7fffebfff700 (LWP 13035)]
[New Thread 0x7fffeb7fe700 (LWP 13036)]
[New Thread 0x7fffeaffd700 (LWP 13037)]
[New Thread 0x7fffea7fc700 (LWP 13038)]
Detaching after fork from child process 13039.
Detaching after fork from child process 13040.
Detaching after fork from child process 13041.
Detaching after fork from child process 13042.
Detaching after fork from child process 13043.
Detaching after fork from child process 13044.
Detaching after fork from child process 13046.
Detaching after fork from child process 13048.
[Thread 0x7fffea7fc700 (LWP 13038) exited]
[Thread 0x7fffeaffd700 (LWP 13037) exited]
[Thread 0x7fffeb7fe700 (LWP 13036) exited]
[Thread 0x7fffebfff700 (LWP 13035) exited]
[Thread 0x7fffe873c700 (LWP 13034) exited]
[Thread 0x7ffff0f3d700 (LWP 13033) exited]
process 13032 is executing new program: /usr/lib64/icinga2/sbin/icinga2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff7fd8700 (LWP 13050)]
[New Thread 0x7ffff7f97700 (LWP 13051)]
[New Thread 0x7ffff7f56700 (LWP 13052)]
[New Thread 0x7ffff7f15700 (LWP 13053)]
[New Thread 0x7ffff7ed4700 (LWP 13054)]
[New Thread 0x7ffff7e93700 (LWP 13055)]
Detaching after fork from child process 13056.
Detaching after fork from child process 13057.
Detaching after fork from child process 13058.
Detaching after fork from child process 13059.
Detaching after fork from child process 13060.
Detaching after fork from child process 13061.
Detaching after fork from child process 13063.
Detaching after fork from child process 13065.
Detaching after fork from child process 13067.
information/cli: Icinga application loader (version: r2.8.4-1)
information/cli: Loading configuration file(s).
[New Thread 0x7ffff7e52700 (LWP 13069)]
[New Thread 0x7ffff0194700 (LWP 13070)]
[New Thread 0x7ffff0153700 (LWP 13071)]
[New Thread 0x7ffff0112700 (LWP 13072)]
[New Thread 0x7ffff00d1700 (LWP 13073)]
[New Thread 0x7ffff0090700 (LWP 13074)]
[New Thread 0x7ffff004f700 (LWP 13075)]
[New Thread 0x7fffdac91700 (LWP 13076)]
[Thread 0x7fffdac91700 (LWP 13076) exited]
[Thread 0x7ffff0112700 (LWP 13072) exited]
[Thread 0x7ffff004f700 (LWP 13075) exited]
[Thread 0x7ffff00d1700 (LWP 13073) exited]
[Thread 0x7ffff0153700 (LWP 13071) exited]
[Thread 0x7ffff0194700 (LWP 13070) exited]
[Thread 0x7ffff7e52700 (LWP 13069) exited]
[Thread 0x7ffff0090700 (LWP 13074) exited]
information/ConfigItem: Committing config item(s).
[New Thread 0x7fffdac91700 (LWP 13077)]
[New Thread 0x7ffff004f700 (LWP 13078)]
[New Thread 0x7ffff0090700 (LWP 13079)]
[New Thread 0x7ffff00d1700 (LWP 13080)]
[New Thread 0x7ffff0112700 (LWP 13081)]
[New Thread 0x7ffff0153700 (LWP 13082)]
[New Thread 0x7ffff0194700 (LWP 13083)]
[New Thread 0x7ffff7e52700 (LWP 13084)]
information/ApiListener: My API identity: icingamaster1

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff0112700 (LWP 13081)]
0x00007ffff5fbed60 in sha1_block_data_order_avx () from /lib64/libcrypto.so.10
Missing separate debuginfos, use: debuginfo-install boost-program-options-1.53.0-27.el7.x86_64 boost-regex-1.53.0-27.el7.x86_64 boost-system-1.53.0-27.el7.x86_64 boost-thread-1.53.0-27.el7.x86_64 glibc-2.17-222.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-19.el7.x86_64 libcom_err-1.42.9-11.el7.x86_64 libedit-3.0-12.20121213cvs.el7.x86_64 libgcc-4.8.5-28.el7.x86_64 libicu-50.1.2-15.el7.x86_64 libselinux-2.5-12.el7.x86_64 libstdc++-4.8.5-28.el7.x86_64 mariadb-libs-5.5.56-2.el7.x86_64 ncurses-libs-5.9-14.20130511.el7_4.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007ffff5fbed60 in sha1_block_data_order_avx () from /lib64/libcrypto.so.10
#1  0xca62c1d68a62b98e in ?? ()
#2  0xca62d1daca62c6d6 in ?? ()
#3  0xca62c1d5ca62beb5 in ?? ()
#4  0xca62c616ca62e216 in ?? ()
#5  0xca6281d54a62d6b6 in ?? ()
#6  0xca62c094ca62bdd1 in ?? ()
#7  0xca62c1d5ca63461c in ?? ()
#8  0xca61c1d1ca626fcf in ?? ()
#9  0x0000000000000000 in ?? ()
(gdb)  
```

## Your Environment

* Version used (`icinga2 --version`):
r2.8.4-1
* Operating System and version:
RHEL 7.5
* Enabled features (`icinga2 feature list`):
Disabled features: compatlog debuglog elasticsearch gelf graphite livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql influxdb mainlog notification

**Comment by dnsmichi** [comment]
That's fixed inside the snapshot packages, any chance you test them?

**Comment by dnsmichi** [comment]
Duplicate of #6279

**Comment by bardahlm** [comment]
I'll test the snapshot version, just need to clone the server and put it somewhere it won't mess up stuff.

**Comment by bardahlm** [comment]
I'm unable to test on a clone in the near future. My system is up and running after downgrading openssl-libs.
