### ISSUE TITLE
Alpine/libmusl: SegFault on sustained process-check-result calls

### ISSUE THREAD

**Issue by turettn** [Icinga/icinga2#6605]
# Basics
Distro: Alpine 3.8
Installation method:  APK, and compiled from source (debug and release)
Version: r2.9.1-1
Enabled features: api checker debuglog ido-mysql mainlog notification
No web, no director
Stock configuration

# How to reproduce
1. Spin up an stock icinga2 instance on Alpine with the api enabled and IDO-MySQL.
2. Create a host using the API
3. Send process-check-result calls to that host via the API repeatedly.

I found this originally using the APK packages, then reproduced on the most recent build from source.

# GDB output
```
/data/icinga2 # gdb /usr/local/lib64/icinga2/sbin/icinga2 -c /tmp/core
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/lib64/icinga2/sbin/icinga2...done.
[New LWP 3433]
[New LWP 3386]
[New LWP 3406]
[New LWP 3408]
[New LWP 3410]
[New LWP 3415]
[New LWP 3420]
[New LWP 3421]
[New LWP 3422]
[New LWP 3424]
[New LWP 3430]
[New LWP 3431]
[New LWP 3435]
[New LWP 3437]
[New LWP 3432]
[New LWP 3434]
[New LWP 3427]
[New LWP 3426]
[New LWP 3425]
[New LWP 3423]
[New LWP 3409]
[New LWP 3407]
[New LWP 3574]
[New LWP 3436]

warning: Can't read pathname for load map: No error information.
Core was generated by `/usr/local/lib64/icinga2/sbin/icinga2 --no-stack-rlimit daemon'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fbcb2a19773 in fetestexcept () from /lib/ld-musl-x86_64.so.1
[Current thread is 1 (LWP 3433)]
(gdb) where
#0  0x00007fbcb2a19773 in fetestexcept () from /lib/ld-musl-x86_64.so.1
Backtrace stopped: Cannot access memory at address 0x7fbcb2ad1e60
(gdb) quit
```

# Client to reproduce error
```python
#!/usr/bin/python3
import requests

AUTH = requests.auth.HTTPBasicAuth('root', '*********') # Not actual passwd
URL = 'https://exec:5665/'
HDR = {'Accept': 'application/json'}

def session():
    sess = requests.Session()
    sess.auth = AUTH
    sess.headers = HDR
    sess.verify = False
    return sess

def create_host():
    data = {'attrs': {"address": "127.0.0.5",
                      "check_command": "dummy"}}
    with session() as sess:
        req = sess.put(URL + "v1/objects/hosts/host1", json=data)
        print(req.status_code)
        print(req.json())

def update_host_status():
    data = {'exit_status': 0,
            'plugin_output': "asdf"}
    params = {'serivce': "host1", "type": "Host"}
    with session() as sess:
        url = URL + "v1/actions/process-check-result"
        req = sess.post(url, json=data, params=params)
        print(req.status_code)
        print(req.json())


if __name__ == '__main__':
    create_host()
    while True:
        update_host_status()
        # Error also occurs with a 0.25 second sleep here
```

# Attached
* [icinga2.log](https://github.com/Icinga/icinga2/files/2363532/icinga2.log)
* [debug.log](https://github.com/Icinga/icinga2/files/2363531/debug.log)
* No crash log was written
* [Core Dump](https://github.com/Icinga/icinga2/files/2363534/core.zip)

**Comment by dnsmichi** [comment]
Note for others: Involves getting an Alpine container which uses libmusl instead of libc. 

If this is reproducible, please generate a full backtrace from gdb.

**Comment by dnsmichi** [comment]
```
docker run -ti alpine sh
echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories
echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
apk update
apk add icinga2 vim curl

icinga2 api setup
vim /etc/icinga2/conf.d/api-users.conf

password = "icinga"

/usr/lib/icinga2/prepare-dirs /etc/icinga2/icinga2.sysconfig

icinga2 daemon &
kill -HUP $(pidof icinga2)

apk add python3 py3-pip py3-requests

vim test.py

#!/usr/bin/python3
import requests

AUTH = requests.auth.HTTPBasicAuth('root', '*********') # Not actual passwd
URL = 'https://exec:5665/'
HDR = {'Accept': 'application/json'}

def session():
    sess = requests.Session()
    sess.auth = AUTH
    sess.headers = HDR
    sess.verify = False
    return sess

def create_host():
    data = {'attrs': {"address": "127.0.0.5",
                      "check_command": "dummy"}}
    with session() as sess:
        req = sess.put(URL + "v1/objects/hosts/host1", json=data)
        print(req.status_code)
        print(req.json())

def update_host_status():
    data = {'exit_status': 0,
            'plugin_output': "asdf"}
    params = {'serivce': "host1", "type": "Host"}
    with session() as sess:
        url = URL + "v1/actions/process-check-result"
        req = sess.post(url, json=data, params=params)
        print(req.status_code)
        print(req.json())


if __name__ == '__main__':
    create_host()
    while True:
        update_host_status()
        # Error also occurs with a 0.25 second sleep here

chmod +x test.py
./test.py
```

I was able to get Python 3 running somehow inside Alpine, but that's horribly broken with libmusl (get random is missing as a symbol for instance).

I wasn't able to reproduce the problem either, Icinga 2 doesn't crash with 2.9.2-r0 on this platform.

**Comment by lippserd** [comment]
Sorry but we can't help you here any further.
