### ISSUE TITLE
BananaPi/armhf: Segmentation fault after building icinga2

### ISSUE THREAD

**Issue by SynPrime** [Icinga/icinga2#6644]
## Expected Behavior

I would like to start icinga2 after building on a BananaPi Pro.

## Current Behavior

If I call icinga2, i get a segmentation fault:

`/server/icinga/tmp/sbin/icinga2`

`[1]    4670 segmentation fault  /server/icinga/tmp/sbin/icinga2`

## Steps to Reproduce (for bugs)
1. build icinga with following cmake options:

```
cmake .. -DCMAKE_INSTALL_PREFIX="/server/icinga/tmp" \
-DICINGA2_WITH_PGSQL=OFF \
-DICINGA2_UNITY_BUILD=OFF \
-DCMAKE_BUILD_TYPE=Debug \
-DICINGA2_PLUGINDIR="/server/icinga/tmp/libexec"

```
2. `make` and `make install`
3. call icinga2 as stated above
4.  `[1]    4670 segmentation fault  /server/icinga/tmp/sbin/icinga2`

## gdb
As you can see, I started icinga2 in gdb:

`gdb /server/icinga/tmp/lib/icinga2/sbin/icinga2`

`run` in gdb

```
Starting program: /home/icinga/tmp/lib/icinga2/sbin/icinga2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x007d97b6 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_local_data (this=<optimized out>) at /usr/include/c++/6/bits/basic_string.h:142
142             return std::pointer_traits<pointer>::pointer_to(*_M_local_buf);
```

`bt` in gdb

```
#0  0x007d97b6 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_local_data (this=<optimized out>) at /usr/include/c++/6/bits/basic_string.h:142
#1  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (__str=..., this=0xc0b600) at /usr/include/c++/6/bits/basic_string.h:399
#2  icinga::String::String (this=0xc0b600, other=...) at /server/icinga/src/icinga2/lib/base/string.cpp:50
#3  0x0078b498 in std::pair<icinga::String const, icinga::Value>::pair (this=0xc0b600) at /usr/include/c++/6/bits/stl_pair.h:288
#4  __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<icinga::String const, icinga::Value> > >::construct<std::pair<icinga::String const, icinga::Value>, std::pair<icinga::String const,
icinga::Value> const&> (this=<optimized out>, __p=<optimized out>) at /usr/include/c++/6/ext/new_allocator.h:120
#5  std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<icinga::String const, icinga::Value> > > >::construct<std::pair<icinga::String const, icinga::Value>, std::pair<icinga::String const, icinga::Value> const&> (__a=..., __p=<optimized out>) at /usr/include/c++/6/bits/alloc_traits.h:475
#6  std::_Rb_tree<icinga::String, std::pair<icinga::String const, icinga::Value>, std::_Select1st<std::pair<icinga::String const, icinga::Value> >, std::less<icinga::String>, std::allocator<std::pair<icinga::String const, icinga::Value> > >::_M_construct_node<std::pair<icinga::String const, icinga::Value> const&> (this=<optimized out>, __node=0xc0b5f0)
    at /usr/include/c++/6/bits/stl_tree.h:543
#7  std::_Rb_tree<icinga::String, std::pair<icinga::String const, icinga::Value>, std::_Select1st<std::pair<icinga::String const, icinga::Value> >, std::less<icinga::String>, std::allocator<std::pair<icinga::String const, icinga::Value> > >::_M_create_node<std::pair<icinga::String const, icinga::Value> const&> (this=<optimized out>) at /usr/include/c++/6/bits/stl_tree.h:560
#8  std::_Rb_tree<icinga::String, std::pair<icinga::String const, icinga::Value>, std::_Select1st<std::pair<icinga::String const, icinga::Value> >, std::less<icinga::String>, std::allocator<std::pair<icinga::String const, icinga::Value> > >::_Alloc_node::operator()<std::pair<icinga::String const, icinga::Value> const&> (this=<synthetic pointer>, __arg=...)
    at /usr/include/c++/6/bits/stl_tree.h:473
#9  std::_Rb_tree<icinga::String, std::pair<icinga::String const, icinga::Value>, std::_Select1st<std::pair<icinga::String const, icinga::Value> >, std::less<icinga::String>, std::allocator<std::pair<icinga::String const, icinga::Value> > >::_M_insert_<std::pair<icinga::String const, icinga::Value> const&, std::_Rb_tree<icinga::String, std::pair<icinga::String const, icinga::Value>, std::_Select1st<std::pair<icinga::String const, icinga::Value> >, std::less<icinga::String>, std::allocator<std::pair<icinga::String const, icinga::Value> > >::_Alloc_node> (
    __node_gen=<synthetic pointer>..., __v=..., __p=0xc0b5d0, __x=0x0, this=0xc0b5cc) at /usr/include/c++/6/bits/stl_tree.h:1535
#10 std::_Rb_tree<icinga::String, std::pair<icinga::String const, icinga::Value>, std::_Select1st<std::pair<icinga::String const, icinga::Value> >, std::less<icinga::String>, std::allocator<std::pair<icinga::String const, icinga::Value> > >::_M_insert_unique_<std::pair<icinga::String const, icinga::Value> const&, std::_Rb_tree<icinga::String, std::pair<icinga::String const, icinga::Value>, std::_Select1st<std::pair<icinga::String const, icinga::Value> >, std::less<icinga::String>, std::allocator<std::pair<icinga::String const, icinga::Value> > >::_Alloc_node> (
    __node_gen=<synthetic pointer>..., __v=..., __position=..., this=0xc0b5cc) at /usr/include/c++/6/bits/stl_tree.h:2004
#11 std::_Rb_tree<icinga::String, std::pair<icinga::String const, icinga::Value>, std::_Select1st<std::pair<icinga::String const, icinga::Value> >, std::less<icinga::String>, std::allocator<std::pair<icinga::String const, icinga::Value> > >::_M_insert_unique<std::pair<icinga::String const, icinga::Value> const*> (__last=<optimized out>, __first=0x0, this=0xc0b5cc)
    at /usr/include/c++/6/bits/stl_tree.h:2250
#12 std::map<icinga::String, icinga::Value, std::less<icinga::String>, std::allocator<std::pair<icinga::String const, icinga::Value> > >::map (__a=..., __comp=..., __l=..., this=0xc0b5cc)
    at /usr/include/c++/6/bits/stl_map.h:215
#13 icinga::Dictionary::Dictionary (this=0xc0b5c0, init=...) at /server/icinga/src/icinga2/lib/base/dictionary.cpp:46
#14 0x0078e456 in icinga::Dictionary::GetPrototype () at /server/icinga/src/icinga2/lib/base/dictionary-script.cpp:123
#15 0x0078ab00 in (anonymous namespace)::io0::<lambda()>::operator() (__closure=0x0) at /server/icinga/src/icinga2/lib/base/dictionary.cpp:31
#16 (anonymous namespace)::io0::<lambda()>::_FUN(void) () at /server/icinga/src/icinga2/lib/base/dictionary.cpp:31
#17 0x007a8242 in std::function<void ()>::operator()() const (this=0xbefff204) at /usr/include/c++/6/functional:2127
#18 icinga::DeferredInitializer::operator() (this=0xbefff204) at /server/icinga/src/icinga2/lib/base/loader.hpp:45
#19 icinga::Loader::ExecuteDeferredInitializers () at /server/icinga/src/icinga2/lib/base/loader.cpp:41
#20 0x0075b4a2 in icinga::Application::InitializeBase () at /server/icinga/src/icinga2/lib/base/application.cpp:139
#21 0x00743ff6 in main (argc=1, argv=0xbefff474) at /server/icinga/src/icinga2/icinga-app/icinga.cpp:841
```

## Your Environment
* Version used (`icinga2 --version`): v2.9.2
* Operating System and version: Debian 9 (Stretch)
* RAM: 1GB (10.3GB Swap)
* Architecture: armhf

The system is running on a BananaPi Pro.

Can you help me to solve the problem?

**Comment by Crunsher** [comment]
I'm not sure we can help with this :(
We are not supporting armhf officially and don't even have ways of reproducing this. If you find a fix or can identify the issue we are happy to help or receive a pull request still.

**Comment by dnsmichi** [comment]
Which compiler/linker is used here?

**Comment by SynPrime** [comment]
> Which compiler/linker is used here?

gcc (Debian 6.3.0-18+deb9u1) 6.3.0

**Comment by dnsmichi** [comment]
Hmmm, Google lead me to this issue which could be related to libstdc++. I don't have an armhf hardware here, so it is a blind guess.

https://github.com/golang/go/issues/20089#issuecomment-300288668

**Comment by dnsmichi** [comment]
I've seen similar crashes in #6761 and #6760, but the obvious question is if there are different compilation flags and behaviours in gcc 6.3 on armhf. E.g. putting ccache up front removed such for weird reasons. I would also try whether a newer gcc version (7.x) or clang++ can solve this problem too.

**Comment by SynPrime** [comment]
Works with gcc version 7.3 and icinga v2.10.2. Thanks for your help!
