### ISSUE TITLE
icinga2 fails to install 2.10.5-1 on centos7

### ISSUE THREAD

**Issue by mbassett** [Icinga/icinga2#7240]
## Describe the bug
fails to install on centos7.    2.10.4 installs without issue.

## To Reproduce
yum install icinga2  on a centos7 box

## Expected behavior
icinga2 installs
## Screenshots
Resolving Dependencies
--> Running transaction check
---> Package icinga2.x86_64 0:2.10.4-1.el7.icinga will be updated
---> Package icinga2.x86_64 0:2.10.5-1.el7.icinga will be an update
--> Processing Dependency: icinga2-bin = 2.10.5-1.el7.icinga for package: icinga2-2.10.5-1.el7.icinga.x86_64
--> Processing Dependency: icinga2-common = 2.10.5-1.el7.icinga for package: icinga2-2.10.5-1.el7.icinga.x86_64
--> Running transaction check
---> Package icinga2-bin.x86_64 0:2.10.4-1.el7.icinga will be updated
---> Package icinga2-bin.x86_64 0:2.10.5-1.el7.icinga will be an update
--> Processing Dependency: libyajl.so.2()(64bit) for package: icinga2-bin-2.10.5-1.el7.icinga.x86_64
Traceback (most recent call last):
  File "/bin/yum", line 29, in <module>
    yummain.user_main(sys.argv[1:], exit_code=True)
  File "/usr/share/yum-cli/yummain.py", line 375, in user_main
    errcode = main(args)
  File "/usr/share/yum-cli/yummain.py", line 239, in main
    (result, resultmsgs) = base.buildTransaction() 
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1198, in buildTransaction
    (rescode, restring) = self.resolveDeps()
  File "/usr/lib/python2.7/site-packages/yum/depsolve.py", line 893, in resolveDeps
    CheckDeps, checkinstalls, checkremoves, missing = self._resolveRequires(errors)
  File "/usr/lib/python2.7/site-packages/yum/depsolve.py", line 1025, in _resolveRequires
    (checkdep, missing, errormsgs) = self._processReq(po, dep)
  File "/usr/lib/python2.7/site-packages/yum/depsolve.py", line 350, in _processReq
    CheckDeps, missingdep = self._requiringFromTransaction(po, requirement, errormsgs)
  File "/usr/lib/python2.7/site-packages/yum/depsolve.py", line 680, in _requiringFromTransaction
    rel=pkg.rel)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 5280, in update
    availpkgs = self._compare_providers(availpkgs, requiringPo)
  File "/usr/lib/python2.7/site-packages/yum/depsolve.py", line 1648, in _compare_providers
    bestnum = max(pkgresults.values())
ValueError: max() arg is an empty sequence

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`):
* Operating System and version: centos7 latest x86_64
* Enabled features (`icinga2 feature list`):
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by peteeckel** [comment]
No problem here (tested on a freshly installed Vagrant box):

```
[vagrant@localhost ~]$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
```

```
[vagrant@localhost ~]$ wget  https://packages.icinga.com/epel/ICINGA-release.repo
--2019-06-14 08:31:10--  https://packages.icinga.com/epel/ICINGA-release.repo
Resolving packages.icinga.com (packages.icinga.com)... 185.11.254.87
Connecting to packages.icinga.com (packages.icinga.com)|185.11.254.87|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 190
Saving to: ‘ICINGA-release.repo’

100%[==========================================================================================>] 190         --.-K/s   in 0s      

2019-06-14 08:31:11 (4.94 MB/s) - ‘ICINGA-release.repo’ saved [190/190]
```

```
[vagrant@localhost ~]$ sudo mv ICINGA-release.repo /etc/yum.repos.d/
```

```
[vagrant@localhost ~]$ sudo yum install icinga2 
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrordenver.fdcservers.net
 * extras: ftp.hosteurope.de
 * updates: mirror.23media.com
icinga-stable-release                                                                                        | 2.9 kB  00:00:00     
icinga-stable-release/7/primary_db                                                                           | 180 kB  00:00:01     
Resolving Dependencies
--> Running transaction check
---> Package icinga2.x86_64 0:2.10.5-1.el7.icinga will be installed
--> Processing Dependency: icinga2-bin = 2.10.5-1.el7.icinga for package: icinga2-2.10.5-1.el7.icinga.x86_64
--> Processing Dependency: icinga2-common = 2.10.5-1.el7.icinga for package: icinga2-2.10.5-1.el7.icinga.x86_64
--> Running transaction check
---> Package icinga2-bin.x86_64 0:2.10.5-1.el7.icinga will be installed
--> Processing Dependency: libyajl.so.2()(64bit) for package: icinga2-bin-2.10.5-1.el7.icinga.x86_64
--> Processing Dependency: libboost_thread-mt.so.1.53.0()(64bit) for package: icinga2-bin-2.10.5-1.el7.icinga.x86_64
--> Processing Dependency: libboost_regex-mt.so.1.53.0()(64bit) for package: icinga2-bin-2.10.5-1.el7.icinga.x86_64
--> Processing Dependency: libboost_system-mt.so.1.53.0()(64bit) for package: icinga2-bin-2.10.5-1.el7.icinga.x86_64
--> Processing Dependency: libboost_program_options-mt.so.1.53.0()(64bit) for package: icinga2-bin-2.10.5-1.el7.icinga.x86_64
---> Package icinga2-common.x86_64 0:2.10.5-1.el7.icinga will be installed
--> Running transaction check
---> Package boost-program-options.x86_64 0:1.53.0-27.el7 will be installed
---> Package boost-regex.x86_64 0:1.53.0-27.el7 will be installed
--> Processing Dependency: libicuuc.so.50()(64bit) for package: boost-regex-1.53.0-27.el7.x86_64
--> Processing Dependency: libicui18n.so.50()(64bit) for package: boost-regex-1.53.0-27.el7.x86_64
--> Processing Dependency: libicudata.so.50()(64bit) for package: boost-regex-1.53.0-27.el7.x86_64
---> Package boost-system.x86_64 0:1.53.0-27.el7 will be installed
---> Package boost-thread.x86_64 0:1.53.0-27.el7 will be installed
---> Package yajl.x86_64 0:2.0.4-4.el7 will be installed
--> Running transaction check
---> Package libicu.x86_64 0:50.1.2-17.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================================================
 Package                            Arch                Version                            Repository                          Size
====================================================================================================================================
Installing:
 icinga2                            x86_64              2.10.5-1.el7.icinga                icinga-stable-release               29 k
Installing for dependencies:
 boost-program-options              x86_64              1.53.0-27.el7                      base                               156 k
 boost-regex                        x86_64              1.53.0-27.el7                      base                               300 k
 boost-system                       x86_64              1.53.0-27.el7                      base                                40 k
 boost-thread                       x86_64              1.53.0-27.el7                      base                                57 k
 icinga2-bin                        x86_64              2.10.5-1.el7.icinga                icinga-stable-release              3.2 M
 icinga2-common                     x86_64              2.10.5-1.el7.icinga                icinga-stable-release              140 k
 libicu                             x86_64              50.1.2-17.el7                      base                               6.9 M
 yajl                               x86_64              2.0.4-4.el7                        base                                39 k

Transaction Summary
====================================================================================================================================
Install  1 Package (+8 Dependent packages)

Total download size: 11 M
Installed size: 41 M
Is this ok [y/d/N]: y
Downloading packages:
(1/9): boost-program-options-1.53.0-27.el7.x86_64.rpm                                                        | 156 kB  00:00:02     
(2/9): boost-system-1.53.0-27.el7.x86_64.rpm                                                                 |  40 kB  00:00:00     
(3/9): boost-regex-1.53.0-27.el7.x86_64.rpm                                                                  | 300 kB  00:00:03     
(4/9): boost-thread-1.53.0-27.el7.x86_64.rpm                                                                 |  57 kB  00:00:00     
warning: /var/cache/yum/x86_64/7/icinga-stable-release/packages/icinga2-2.10.5-1.el7.icinga.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 34410682: NOKEY
Public key for icinga2-2.10.5-1.el7.icinga.x86_64.rpm is not installed
(5/9): icinga2-2.10.5-1.el7.icinga.x86_64.rpm                                                                |  29 kB  00:00:01     
(6/9): icinga2-common-2.10.5-1.el7.icinga.x86_64.rpm                                                         | 140 kB  00:00:03     
(7/9): yajl-2.0.4-4.el7.x86_64.rpm                                                                           |  39 kB  00:00:04     
(8/9): icinga2-bin-2.10.5-1.el7.icinga.x86_64.rpm                                                            | 3.2 MB  00:00:48     
(9/9): libicu-50.1.2-17.el7.x86_64.rpm                                                                       | 6.9 MB  00:01:07     
------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                               151 kB/s |  11 MB  00:01:13     
Retrieving key from https://packages.icinga.com/icinga.key
Importing GPG key 0x34410682:
 Userid     : "Icinga Open Source Monitoring (Build server) <info@icinga.org>"
 Fingerprint: f51a 91a5 ee00 1aa5 d77d 53c4 c6e3 19c3 3441 0682
 From       : https://packages.icinga.com/icinga.key
Is this ok [y/N]: y
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : boost-system-1.53.0-27.el7.x86_64                                                                                1/9 
  Installing : boost-thread-1.53.0-27.el7.x86_64                                                                                2/9 
  Installing : boost-program-options-1.53.0-27.el7.x86_64                                                                       3/9 
  Installing : yajl-2.0.4-4.el7.x86_64                                                                                          4/9 
  Installing : libicu-50.1.2-17.el7.x86_64                                                                                      5/9 
  Installing : boost-regex-1.53.0-27.el7.x86_64                                                                                 6/9 
  Installing : icinga2-bin-2.10.5-1.el7.icinga.x86_64                                                                           7/9 
  Installing : icinga2-common-2.10.5-1.el7.icinga.x86_64                                                                        8/9 
  Installing : icinga2-2.10.5-1.el7.icinga.x86_64                                                                               9/9 
  Verifying  : boost-system-1.53.0-27.el7.x86_64                                                                                1/9 
  Verifying  : icinga2-common-2.10.5-1.el7.icinga.x86_64                                                                        2/9 
  Verifying  : libicu-50.1.2-17.el7.x86_64                                                                                      3/9 
  Verifying  : boost-regex-1.53.0-27.el7.x86_64                                                                                 4/9 
  Verifying  : icinga2-2.10.5-1.el7.icinga.x86_64                                                                               5/9 
  Verifying  : boost-thread-1.53.0-27.el7.x86_64                                                                                6/9 
  Verifying  : yajl-2.0.4-4.el7.x86_64                                                                                          7/9 
  Verifying  : boost-program-options-1.53.0-27.el7.x86_64                                                                       8/9 
  Verifying  : icinga2-bin-2.10.5-1.el7.icinga.x86_64                                                                           9/9 

Installed:
  icinga2.x86_64 0:2.10.5-1.el7.icinga                                                                                              

Dependency Installed:
  boost-program-options.x86_64 0:1.53.0-27.el7 boost-regex.x86_64 0:1.53.0-27.el7       boost-system.x86_64 0:1.53.0-27.el7        
  boost-thread.x86_64 0:1.53.0-27.el7          icinga2-bin.x86_64 0:2.10.5-1.el7.icinga icinga2-common.x86_64 0:2.10.5-1.el7.icinga
  libicu.x86_64 0:50.1.2-17.el7                yajl.x86_64 0:2.0.4-4.el7               

Complete!
```

**Comment by Crunsher** [comment]
There is a topic on this on the community boards with a workaround: https://community.icinga.com/t/update-icinga-2-10-5-1/1300

**Comment by dnsmichi** [comment]
This only happens if you have not removed the obsolete `icinga2-libs` package yet, provided with 2.8.4 at last. Manually purge this package and you're good to go.

**Comment by mbassett** [comment]
I do not have icinga2-libs installed, and still have this issue with 2.10.5.1

**Comment by seffparker** [comment]
Mine was not related to yajl, but the epel wasn't enabled in repo configuration. Changed to enabled=1 and installed successfully.
