### ISSUE TITLE
2.11 RC downtime planning shows problems with default times

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icinga2#7384]
## Describe the bug

When I try to schedule a downtime, sometimes I get the following error message:

```
icinga2: Can't send external Icinga command: 400 Options 'start_time' and 'end_time' must be greater than current timestamp.
```

with the following stacktrace in Icinga Web 2 (2.7)

```
#0 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/ScheduleServiceDowntimeCommandForm.php(192): Icinga\Module\Monitoring\Command\Transport\CommandTransport->send(Object(Icinga\Module\Monitoring\Command\Object\ScheduleHostDowntimeCommand))
#1 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/ScheduleHostDowntimeCommandForm.php(113): Icinga\Module\Monitoring\Forms\Command\Object\ScheduleServiceDowntimeCommandForm->scheduleDowntime(Object(Icinga\Module\Monitoring\Command\Object\ScheduleHostDowntimeCommand), Object(Icinga\Web\Request))
#2 /usr/share/php/Icinga/Web/Form.php(1171): Icinga\Module\Monitoring\Forms\Command\Object\ScheduleHostDowntimeCommandForm->onSuccess()
#3 /usr/share/icingaweb2/modules/monitoring/application/controllers/HostsController.php(80): Icinga\Web\Form->handleRequest()
#4 /usr/share/icingaweb2/modules/monitoring/application/controllers/HostsController.php(232): Icinga\Module\Monitoring\Controllers\HostsController->handleCommandForm(Object(Icinga\Module\Monitoring\Forms\Command\Object\ScheduleHostDowntimeCommandForm))
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\HostsController->scheduleDowntimeAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}
```

## To Reproduce

I had this problem in the following situations:

* Planning a downtime for multiple hosts (including their services)
* Planning a downtime for one service and changing the end date

It did not occur every time but at least every second time I plan a downtime in Icinga Web 2

* Plan a downtime
* Leave Times and "fixed" As is
* Write a comment for the downtime
* Hit Schedule downtime

## Expected behavior
The downtime gets planned.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`): 2.11 RC1
* Operating System and version: CentOS 7
* Icinga Web 2 version and modules (System - About): 2.7

**Comment by dnsmichi** [comment]
I see, thanks. I have hardened the validation for the API, seems that web sets a start time in the past. Since this may be relevant for "sla beschiss", I'll revert the changes.
