### ISSUE TITLE
Icinga adds another LC_NUMERIC=C environment variable everytime a reload is fired.

### ISSUE THREAD

**Issue by NeverUsedID** [Icinga/icinga2#7405]
## Describe the bug

Everytime Icinga reloads, it adds another LC_NUMERIC=C to the envrionment Variables.

Example printenv output while printenv is used as a check command:

```
LANGUAGE=en_US:en
NOTIFY_SOCKET=/run/systemd/notify
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
LANG=en_US.UTF-8
PWD=/
ICINGA2_ERROR_LOG=/var/log/icinga2/error.log
LC_NUMERIC=C
LC_NUMERIC=C
LC_NUMERIC=C
LC_NUMERIC=C
LC_NUMERIC=C
LC_NUMERIC=C
[...]
```
An Icinga restart cleans the environment variables again:

```
LANGUAGE=en_US:en
NOTIFY_SOCKET=/run/systemd/notify
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
LANG=en_US.UTF-8
PWD=/
ICINGA2_ERROR_LOG=/var/log/icinga2/error.log
LC_NUMERIC=C
```

## To Reproduce
Create a check that execute prtintenv and reload Icinga2

## Expected behavior
Only one LC_NUMERIC Value should be set at any time..

## Your Environment
Ubuntu 16.04.6 LTS (Xenial Xerus)
Icinga2  r2.10.5-1
Enabled features: api checker command ido-mysql mainlog perfdata

## Additional context
The problem on my side: I'am using some Powershell scripts under Linux. Powershell does not allow duplicate Environment variables. As a result every Powershellcheck goes "UNKNOWN".

Powershell Error example:
```

FailFast:
The type initializer for 'Microsoft.PowerShell.ApplicationInsightsTelemetry' threw an exception.

   at System.Environment.FailFast(System.String, System.Exception)
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])

Exception details:
System.TypeInitializationException: The type initializer for 'Microsoft.PowerShell.ApplicationInsightsTelemetry' threw an exception. ---> System.ArgumentException: Item has already been added. Key in dictionary: 'LC_NUMERIC'  Key being added: 'LC_NUMERIC'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Environment.ToHashtable(IEnumerable`1 pairs)
   at System.Environment.GetEnvironmentVariables()
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Platform.PlatformImplementation..ctor()
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Platform.PlatformSingleton.get_Current()
   at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.Initialize(TelemetryConfiguration configuration, TelemetryModules modules)
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.get_Active()
   at Microsoft.PowerShell.ApplicationInsightsTelemetry..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.ApplicationInsightsTelemetry.SendPSCoreStartupTelemetry()
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc)
<Terminated by signal 6 (Aborted).>
```

**Comment by dnsmichi** [comment]
Interesting finding. This only happens with reloads though, right? You might want to give the 2.11 RC1 package a try where we've improved the reload handling (and I hope that the environment is not populated twice).

https://icinga.com/2019/07/25/icinga-2-11-release-candidate/

**Comment by NeverUsedID** [comment]
Yes, only on reload. Just tested the RC1. Problem is solved there.

Thanks for fast suppport!

**Comment by dnsmichi** [comment]
Awesome, thanks for the fast testing 👍
