### ISSUE TITLE
ScheduledDowtime provides "Error: getrandom"

### ISSUE THREAD

**Issue by pluhin** [Icinga/icinga2#7621]
## Describe the bug

After upgrading from icinga 2.10.4 to 2.11 on RH 7.3 cannot create/apply ScheduledDowntime objects.

## To Reproduce

1. Create by curl request ScheduledDowntime was failed
2. Changing configuration on master and apply was failed
3. Web UI returned 500 state

## Expected behavior

Create/apply ScheduledDowntime objects

## Screenshots

![Screenshot from 2019-11-13 10-22-44](https://user-images.githubusercontent.com/8258487/68750781-bc787900-0600-11ea-9c1c-0ce8be850355.png)

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Version used (`icinga2 --version`):

```bash
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.2-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.3 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-514.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-LTrJQZ9N-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* Operating System and version:

```bash
# cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"
```

* Enabled features (`icinga2 feature list`):

```bash
 # icinga2 feature list
Disabled features: compatlog debuglog elasticsearch gelf ido-mysql influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command graphite ido-pgsql mainlog notification
```
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
```
[2019-11-13 10:33:19 +0100] information/cli: Icinga application loader (version: 2.11.2-1)
[2019-11-13 10:33:19 +0100] information/cli: Loading configuration file(s).
[2019-11-13 10:33:19 +0100] information/ConfigItem: Committing config item(s).
[2019-11-13 10:33:19 +0100] information/ApiListener: My API identity: MT_tst_icinga2_1
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 17 ScheduledDowntimes.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 6 NotificationCommands.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 4748 Notifications.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 13 HostGroups.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 225 Hosts.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 1 GraphiteWriter.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 222 Zones.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 225 Endpoints.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 1 ApiUser.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 5 UserGroups.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 250 CheckCommands.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 1 IdoPgsqlConnection.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 5 TimePeriods.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 6 Users.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 1913 Services.
[2019-11-13 10:33:20 +0100] information/ConfigItem: Instantiated 8 ServiceGroups.
[2019-11-13 10:33:20 +0100] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2019-11-13 10:33:20 +0100] information/cli: Finished validating the configuration file(s).

```

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

## Additional context

```
Caught unhandled exception.
Current time: 2019-09-27 12:52:38 +0200

  Application version: 2.11.0-1

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.3 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-514.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-LTrJQZ9N-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

Error: getrandom

        (0) icinga2: icinga::CreateCert(evp_pkey_st*, X509_name_st*, X509_name_st*, evp_pkey_st*, bool) (+0x9e) [0xbde21e]
        (1) icinga2: icinga::CreateCertIcingaCA(evp_pkey_st*, X509_name_st*) (+0xec) [0xbdea9c]
        (2) icinga2: icinga::CreateCertIcingaCA(std::shared_ptr<x509_st> const&) (+0x65) [0xbdee85]
        (3) icinga2: icinga::CASignCommand::Run(boost::program_options::variables_map const&, std::vector<std::string, std::allocator<std::string> > const&) const (+0x30b) [0x93765b]
        (4) /usr/lib64/icinga2/sbin/icinga2() [0xb30283]
        (5) icinga2: main (+0xb8) [0x5fff28]
        (6) libc.so.6: __libc_start_main (+0xf5) [0x7f7e585edb35]
        (7) /usr/lib64/icinga2/sbin/icinga2() [0x6029e3]


***
* This would indicate a runtime problem or configuration error. If you believe this is a bug in Icinga 2
* please submit a bug report at https://github.com/Icinga/icinga2 and include this stack trace as well as any other
* information that might be useful in order to reproduce this problem.
***
[New LWP 23560]
[New LWP 23559]
[New LWP 23558]
[New LWP 23557]
[New LWP 23556]
[New LWP 23555]
[New LWP 23554]
[New LWP 23553]
[New LWP 23552]
[New LWP 23551]
[New LWP 23550]
[New LWP 23549]
[New LWP 23548]
[New LWP 23547]
[New LWP 23546]
[New LWP 23545]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007f7e5899bf19 in waitpid () from /lib64/libpthread.so.0

Thread 17 (Thread 0x7f7e53a7d700 (LWP 23545)):
#0  0x00007f7e589986d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000637aec in boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .local.25181] ()
No symbol table info available.
#2  0x0000000000637fa2 in boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run() [clone .local.25179] ()
No symbol table info available.
#3  0x000000000082e3ef in boost_asio_detail_posix_thread_function ()
No symbol table info available.
#4  0x00007f7e58994dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f7e586c373d in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 16 (Thread 0x7f7e53abe700 (LWP 23546)):
#0  0x00007f7e589986d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000637aec in boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .local.25181] ()
No symbol table info available.
#2  0x0000000000637fa2 in boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run() [clone .local.25179] ()
No symbol table info available.
#3  0x000000000082e3ef in boost_asio_detail_posix_thread_function ()
No symbol table info available.
#4  0x00007f7e58994dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f7e586c373d in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 15 (Thread 0x7f7e53aff700 (LWP 23547)):
#0  0x00007f7e589986d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000637aec in boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .local.25181] ()
No symbol table info available.
#2  0x0000000000637fa2 in boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run() [clone .local.25179] ()
No symbol table info available.
#3  0x000000000082e3ef in boost_asio_detail_posix_thread_function ()
No symbol table info available.
#4  0x00007f7e58994dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f7e586c373d in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 14 (Thread 0x7f7e5b349700 (LWP 23548)):
#0  0x00007f7e589986d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000637aec in boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .local.25181] ()
No symbol table info available.
#2  0x0000000000637fa2 in boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run() [clone .local.25179] ()
No symbol table info available.
#3  0x000000000082e3ef in boost_asio_detail_posix_thread_function ()
No symbol table info available.
#4  0x00007f7e58994dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f7e586c373d in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 13 (Thread 0x7f7e5b38a700 (LWP 23549)):
#0  0x00007f7e589986d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000637aec in boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .local.25181] ()
No symbol table info available.
#2  0x0000000000637fa2 in boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run() [clone .local.25179] ()
No symbol table info available.
#3  0x000000000082e3ef in boost_asio_detail_posix_thread_function ()
No symbol table info available.
#4  0x00007f7e58994dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f7e586c373d in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 12 (Thread 0x7f7e5b3cb700 (LWP 23550)):
#0  0x00007f7e589986d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000637aec in boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .local.25181] ()
No symbol table info available.
#2  0x0000000000637fa2 in boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run() [clone .local.25179] ()
No symbol table info available.
#3  0x000000000082e3ef in boost_asio_detail_posix_thread_function ()
No symbol table info available.
#4  0x00007f7e58994dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f7e586c373d in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 11 (Thread 0x7f7e5b40c700 (LWP 23551)):
#0  0x00007f7e589986d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000637aec in boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .local.25181] ()
No symbol table info available.
#2  0x0000000000637fa2 in boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run() [clone .local.25179] ()
No symbol table info available.
#3  0x000000000082e3ef in boost_asio_detail_posix_thread_function ()
No symbol table info available.
#4  0x00007f7e58994dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f7e586c373d in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 10 (Thread 0x7f7e5b44d700 (LWP 23552)):
#0  0x00007f7e589986d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000637aec in boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .local.25181] ()
No symbol table info available.
#2  0x0000000000637fa2 in boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run() [clone .local.25179] ()
No symbol table info available.
#3  0x000000000082e3ef in boost_asio_detail_posix_thread_function ()
No symbol table info available.
#4  0x00007f7e58994dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f7e586c373d in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 9 (Thread 0x7f7e5b48e700 (LWP 23553)):
#0  0x00007f7e589986d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000637aec in boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .local.25181] ()
No symbol table info available.
#2  0x0000000000637fa2 in boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run() [clone .local.25179] ()
No symbol table info available.
#3  0x000000000082e3ef in boost_asio_detail_posix_thread_function ()
No symbol table info available.
#4  0x00007f7e58994dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f7e586c373d in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 8 (Thread 0x7f7e53a3c700 (LWP 23554)):
#0  0x00007f7e589986d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000637aec in boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .local.25181] ()
No symbol table info available.
#2  0x0000000000637fa2 in boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run() [clone .local.25179] ()
No symbol table info available.
#3  0x000000000082e3ef in boost_asio_detail_posix_thread_function ()
No symbol table info available.
#4  0x00007f7e58994dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f7e586c373d in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 7 (Thread 0x7f7e539fb700 (LWP 23555)):
#0  0x00007f7e589986d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000637aec in boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .local.25181] ()
No symbol table info available.
#2  0x0000000000637fa2 in boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run() [clone .local.25179] ()
No symbol table info available.
#3  0x000000000082e3ef in boost_asio_detail_posix_thread_function ()
No symbol table info available.
#4  0x00007f7e58994dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f7e586c373d in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 6 (Thread 0x7f7e539ba700 (LWP 23556)):
#0  0x00007f7e589986d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000637aec in boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .local.25181] ()
No symbol table info available.
#2  0x0000000000637fa2 in boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run() [clone .local.25179] ()
No symbol table info available.
#3  0x000000000082e3ef in boost_asio_detail_posix_thread_function ()
No symbol table info available.
#4  0x00007f7e58994dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f7e586c373d in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 5 (Thread 0x7f7e53979700 (LWP 23557)):
#0  0x00007f7e589986d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000637aec in boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .local.25181] ()
No symbol table info available.
#2  0x0000000000637fa2 in boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run() [clone .local.25179] ()
No symbol table info available.
#3  0x000000000082e3ef in boost_asio_detail_posix_thread_function ()
No symbol table info available.
#4  0x00007f7e58994dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f7e586c373d in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 4 (Thread 0x7f7e53938700 (LWP 23558)):
#0  0x00007f7e589986d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x0000000000637aec in boost::asio::detail::scheduler::run(boost::system::error_code&) [clone .local.25181] ()
No symbol table info available.
#2  0x0000000000637fa2 in boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run() [clone .local.25179] ()
No symbol table info available.
#3  0x000000000082e3ef in boost_asio_detail_posix_thread_function ()
No symbol table info available.
#4  0x00007f7e58994dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f7e586c373d in clone () from /lib64/libc.so.6
No symbol table info available.

....
```

```
curl -k -s -u root:***** -H 'Accept: application/json' -X POST 'https://********:5665/v1/actions/schedule-downtime' -d "$(jo -p pretty=true type=Host filter="match(\"5A_host_02\", host.name)" all_services=true author=icingaadmin comment="VRM migration for AT" fixed=true start_time=$(date +%s -d "+0 hour") end_time=$(date +%s -d "+60 day"))"
{
    "results": [
        {
            "code": 500.0,
            "status": "Action execution failed: 'Error: getrandom\n'."
        }
    ]
}%           
```

**Comment by dnsmichi** [comment]
Same as #7560 - your virtualization host does not implemented required syscalls in the kernel used by the guest system with Boost.
