### ISSUE TITLE
Cannot enable module "command". Module is not installed.

### ISSUE THREAD

**Issue by picnicsecurity** [Icinga/icinga2#8499]
## Describe the bug

On a fresh install of icinga2 and icingaweb2, after adding a host using icinga director following [this guide](https://www.howtoforge.com/how-to-add-hosts-to-icinga2-using-the-icinga-director/), the Dashboard shows the host status as "Unknown". When I try to run "Check now", I get the following error:

```
icinga2: Can't send external Icinga command to the local command file "/var/run/icinga2/cmd/icinga2.cmd": Permission denied.

#0 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/CheckNowCommandForm.php(76): Icinga\Module\Monitoring\Command\Transport\CommandTransport->send(Object(Icinga\Module\Monitoring\Command\Object\ScheduleServiceCheckCommand))
#1 /usr/share/php/Icinga/Web/Form.php(1171): Icinga\Module\Monitoring\Forms\Command\Object\CheckNowCommandForm->onSuccess()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(325): Icinga\Web\Form->handleRequest()
#3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(68): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->setupQuickActionForms()
#4 /usr/share/icingaweb2/modules/monitoring/application/controllers/ServiceController.php(72): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->showAction()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ServiceController->showAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}
```

I looked into this issue and found this [previous issue](https://github.com/Icinga/icinga2/issues/5096).

```
root@AWS-NOC-02:/etc/icinga2/conf.d# icinga2 feature list
Disabled features: command compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker ido-mysql mainlog notification
root@AWS-NOC-02:/etc/icinga2/conf.d# ls -l /var/run/icinga2/cmd
total 0
root@AWS-NOC-02:/etc/icinga2/conf.d# icinga2 object list --type ExternalCommandListener
root@AWS-NOC-02:/etc/icinga2/conf.d# cat /etc/icinga2/features-enabled/command.conf
cat: /etc/icinga2/features-enabled/command.conf: No such file or directory
root@AWS-NOC-02:/etc/icinga2/conf.d# cat /etc/icinga2/icinga2.conf
/**
 * Icinga 2 configuration file
 * - this is where you define settings for the Icinga application including
 * which hosts/services to check.
 *
 * For an overview of all available configuration options please refer
 * to the documentation that is distributed as part of Icinga 2.
 */

/**
 * The constants.conf defines global constants.
 */
include "constants.conf"

/**
 * The zones.conf defines zones for a cluster setup.
 * Not required for single instance setups.
 */
include "zones.conf"

/**
 * The Icinga Template Library (ITL) provides a number of useful templates
 * and command definitions.
 * Common monitoring plugin command definitions are included separately.
 */
include <itl>
include <plugins>
include <plugins-contrib>
include <manubulon>

/**
 * This includes the Icinga 2 Windows plugins. These command definitions
 * are required on a master node when a client is used as command endpoint.
 */
include <windows-plugins>

/**
 * This includes the NSClient++ check commands. These command definitions
 * are required on a master node when a client is used as command endpoint.
 */
include <nscp>

/**
 * The features-available directory contains a number of configuration
 * files for features which can be enabled and disabled using the
 * icinga2 feature enable / icinga2 feature disable CLI commands.
 * These commands work by creating and removing symbolic links in
 * the features-enabled directory.
 */
include "features-enabled/*.conf"

/**
 * Although in theory you could define all your objects in this file
 * the preferred way is to create separate directories and files in the conf.d
 * directory. Each of these files must have the file extension ".conf".
 */
include_recursive "conf.d"
root@AWS-NOC-02:/etc/icinga2/conf.d# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 18.04.5 LTS (Bionic Beaver)
  Kernel: Linux
  Kernel version: 5.4.0-1029-aws
  Architecture: x86_64

Build information:
  Compiler: GNU 7.3.0
  Build host: lcy01-amd64-027
```

So it would appear that my command module is not installed?

```
root@AWS-NOC-02:/etc/icinga2/conf.d# icingacli module enable command
ERROR: Icinga\Exception\ConfigurationError in /usr/share/php/Icinga/Application/Modules/Manager.php:248 with message: Cannot enable module "command". Module is not installed.
```

## Expected behavior

To do basic monitoring (ssh/ping/http/winrm/snmp) of hosts without an agent

## Your Environment

```
root@AWS-NOC-02:/etc/icinga2/conf.d# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 18.04.5 LTS (Bionic Beaver)
  Kernel: Linux
  Kernel version: 5.4.0-1029-aws
  Architecture: x86_64

Build information:
  Compiler: GNU 7.3.0
  Build host: lcy01-amd64-027
```

## Additional context

I am sure that whatever I am doing wrong is relatively basic. This is my first time working with Icinga2 from scratch so I am learning as I go. Any help you are willing to provide would be greatly appreciated. Thanks!

**Comment by Al2Klimov** [comment]
@Yonas-net Please have a look what’s the problem here.

**Comment by Yonas-net** [comment]
You did not enable the Icinga2 cammand feature, probably because Icinga Web 2 cannot find it. Run the following command and it should work. ``icinga2 feature enable command``.

And by the way, if you have just installed Icinga2 anyway, why don't you use the latest release?

**Comment by picnicsecurity** [comment]
Good Afternoon Yonas,

I was not aware I was not using the most recent version. Thank you for pointing that out! These were the commands I used to install icinga2
```
apt update -y && apt upgrade -y && reboot
apt-get -y install apt-transport-https wget gnupg

wget -O - https://packages.icinga.com/icinga.key | apt-key add -

. /etc/os-release; if [ ! -z ${UBUNTU_CODENAME+x} ]; then DIST="${UBUNTU_CODENAME}"; else DIST="$(lsb_release -c| awk '{print $2}')"; fi; \
 echo "deb https://packages.icinga.com/ubuntu icinga-${DIST} main" > \
 /etc/apt/sources.list.d/${DIST}-icinga.list
 echo "deb-src https://packages.icinga.com/ubuntu icinga-${DIST} main" >> \
 /etc/apt/sources.list.d/${DIST}-icinga.list

apt-get update
systemctl enable icinga2
systemctl start icinga2
```
I would assume that using apt would have gotten me the most recent one? Or do I need to do it another way?
```
apt list --installed | grep icinga

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

icinga-l10n/icinga-bionic,now 1.0.0-1.bionic all [installed,automatic]
icinga2/icinga-bionic,now 2.12.1-1.bionic amd64 [installed]
icinga2-bin/icinga-bionic,now 2.12.1-1.bionic amd64 [installed,automatic]
icinga2-common/icinga-bionic,now 2.12.1-1.bionic all [installed,automatic]
icinga2-doc/icinga-bionic,now 2.12.1-1.bionic all [installed,automatic]
icingacli/icinga-bionic,now 2.8.2-1.bionic all [installed]
libboost-context1.67.0-icinga/icinga-bionic,now 1.67.0-13.1.bionic amd64 [installed,automatic]
libboost-coroutine1.67.0-icinga/icinga-bionic,now 1.67.0-13.1.bionic amd64 [installed,automatic]
libboost-filesystem1.67.0-icinga/icinga-bionic,now 1.67.0-13.1.bionic amd64 [installed,automatic]
libboost-program-options1.67.0-icinga/icinga-bionic,now 1.67.0-13.1.bionic amd64 [installed,automatic]
libboost-regex1.67.0-icinga/icinga-bionic,now 1.67.0-13.1.bionic amd64 [installed,automatic]
libboost-system1.67.0-icinga/icinga-bionic,now 1.67.0-13.1.bionic amd64 [installed,automatic]
libboost-thread1.67.0-icinga/icinga-bionic,now 1.67.0-13.1.bionic amd64 [installed,automatic]
php-icinga/icinga-bionic,now 2.8.2-1.bionic all [installed,automatic]
```
So apt is showing it as installed but when I check to see if anything is upgradeable it does not list anything?
```
apt list --upgradeable

Listing... Done
```
I believe this file is correct?
```
/etc/apt/sources.list.d# cat bionic-icinga.list
deb https://packages.icinga.com/ubuntu icinga-bionic main
deb-src https://packages.icinga.com/ubuntu icinga-bionic main
```


As for command feature
I am glad that enabling that module was as easy as that command. I enabled it and after a restart I was able to hit check now without issue! Excellent!!! Do you know where in the documentation I could have found that? I am trying to make sure to read through all the documentation before asking questions so I want to see where I missed that.

**Comment by Yonas-net** [comment]
Hello Adam, nice to hear that it worked. Such CLI commands are not part of the installation but they are also in the Icinga documentation with their own [topics](https://icinga.com/docs/icinga2/latest/doc/11-cli-commands/#cli-command-feature).

You can upgrade your Icinga2 like this ``sudo apt-get upgrade icinga2`` then apt will get the latest release.

**Comment by Al2Klimov** [comment]
I consider this problem solved.
