### ISSUE TITLE
Crashes with 2.12.3: invalid opcode

### ISSUE THREAD

**Issue by maelig** [Icinga/icinga2#8713]
## Describe the bug
Hi all!
We have 2 Masters,  4 Zones with 4 Sats Setup.
Several times, the master active crash since 3 days without reason.
```
kernel: [42849547.512376] traps: icinga2[14506] trap invalid opcode ip:7f6b1acbeedc sp:7f6b15f1fdb0 error:0 in libpthread-2.23.so[7f6b1acb2000+18000]
icinga2.service: Main process exited, code=exited, status=132/n/a
icinga2.service: Unit entered failed state.
systemd[1]: icinga2.service: Failed with result exit-code.
```

## To Reproduce
I wish I could reproduce this, but it is irregular.

## Screenshots
![image](https://user-images.githubusercontent.com/7013790/114208663-02548080-995e-11eb-94ed-5ed7925740f0.png)

## Your Environment
```Caught unhandled exception.
Current time: 2020-10-08 10:55:57 +0200  
Application version: r2.11.3-1
System information:
  Platform: Ubuntu
  Platform version: 16.04.6 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.15.0-1063-azure
  Architecture: x86_64
Build information:
  Compiler: GNU 5.4.0
  Build host: runner-LTrJQZ9N-project-298-concurrent-0
Application information:
General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2
Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var
Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
 ```

## Additional context

```
[2021-04-09 18:08:20 +0200] information/cli: Icinga application loader (version: r2.11.3-1)
[2021-04-09 18:08:20 +0200] information/cli: Loading configuration file(s).
[2021-04-09 18:08:20 +0200] information/ConfigItem: Committing config item(s).
[2021-04-09 18:08:20 +0200] information/ApiListener: My API identity: slg-infra-prd-azu-frw-lnx-icinga-001
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 1 InfluxdbWriter.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 1 LivestatusListener.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 536 HostGroups.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 4 EventCommands.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 7 NotificationCommands.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 3415 Notifications.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 1488 Hosts.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 145 Downtimes.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 209 Comments.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 772 Zones.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 771 Endpoints.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 6 ApiUsers.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 859 CheckCommands.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 87 TimePeriods.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 12 UserGroups.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 106 Users.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 10984 Services.
[2021-04-09 18:08:28 +0200] information/ConfigItem: Instantiated 162 ServiceGroups.
[2021-04-09 18:08:29 +0200] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2021-04-09 18:08:29 +0200] information/cli: Finished validating the configuration file(s).
```

**Comment by julianbrost** [comment]
Is the file you posted the only one in `/var/log/icinga2/crash`? From the stack trace, this one is from a call to `icinga2 pki sign-csr` and not the daemon.

**Comment by maelig** [comment]
@julianbrost, sorry, it's a mistake. It is an old crash log (2020-10-08). There is no log for my problem in the directory /var/log/icinga2/crash.

**Comment by julianbrost** [comment]
Is the other information from the crash report still up-to-date, i.e. did the crash happen with Icinga 2.11.3 on Ubuntu 16.04?

Can you check if you can obtain a core dump of the crash? I don't know by heart where they go on Ubuntu 16.04 by default (you can check with `sysctl kernel.core_pattern`), maybe https://icinga.com/docs/icinga-2/latest/doc/21-development/#core-dump provides some useful information.

**Comment by maelig** [comment]
The crash happen with Icinga 2.11.3 on Ubuntu 16.04 often when reload icinga2 service. 
In relation to https://github.com/Icinga/icinga2/issues/7773 ?

**Comment by maelig** [comment]
Unfortunately no, because it is the production

**Comment by Al2Klimov** [comment]
What's the problem?

**Comment by maelig** [comment]
I still have his crach in version 2.12.3-1 :
```
Jan 20 11:00:24 slg-infra-prd-azu-frw-lnx-icinga-002 kernel: [19517125.946113] traps: icinga2[21947] trap invalid opcode ip:7fc015bf1edc sp:7fc0101cba80 error:0 in libpthread-2.23.so[7fc015be5000+18000]
Jan 20 11:16:08 slg-infra-prd-azu-frw-lnx-icinga-002 kernel: [19518069.875923] traps: icinga2[23852] trap invalid opcode ip:7fc33aa3bedc sp:7fc335015a60 error:0 in libpthread-2.23.so[7fc33aa2f000+18000]
```

**Comment by maelig** [comment]
Another crash today ! How can I transfer the core dump file to you ?

**Comment by Al2Klimov** [comment]
https://transfer.netways.de/index.php/s/qXF56x8sYa97iHQ

Do you+us a favor and gzip it first.

**Comment by maelig** [comment]
Sorry, i didn't see your message to compress the file. Dump core file sent : core.icinga2.17661. Thanks

**Comment by Al2Klimov** [comment]
Hmm..

```
Thread 13 (Thread 0x7f70461d6700 (LWP 17676)):
#0  sha256_block_data_order_avx2 () at sha256-x86_64.s:5265
#1  0x4d167cf5dafb4029 in ?? ()
#2  0x744a1117b4a0fefb in ?? ()
#3  0x70101264fa4917ab in ?? ()
#4  0x949d9014fb71e199 in ?? ()
#5  0x6eeff1b9f97f8857 in ?? ()
#6  0x05e8eee4bd5b5c2b in ?? ()
#7  0x353c77b38683890e in ?? ()
#8  0x32677ea2649c082e in ?? ()
---Type <return> to continue, or q <return> to quit---
#9  0x0cd82326ef3f426c in ?? ()
#10 0xd95379e51655fd96 in ?? ()
#11 0x1c4812bc95c5c493 in ?? ()
#12 0x86d1bc633cb308ee in ?? ()
#13 0x631ff3cf1979e41e in ?? ()
#14 0xea2069d1ae93506e in ?? ()
#15 0x729f536f8e88f6e5 in ?? ()
#16 0xde4c5d778e0aeb36 in ?? ()
#17 0xe3973120e705c22a in ?? ()
#18 0x1e1db0a54aa2331e in ?? ()
#19 0xa16511d6b3cbb344 in ?? ()
#20 0xcd57aaca54ec5c4d in ?? ()
#21 0x1a798e588f70e1cd in ?? ()
#22 0x9f5c6cdc5f65d0d8 in ?? ()
#23 0x6b1e140c88dd79a6 in ?? ()
#24 0xbcea72999b9fa7c2 in ?? ()
#25 0xb819f8eac13b2eb9 in ?? ()
#26 0x7961fe7a1e031a22 in ?? ()
#27 0x0decb7c7b1367909 in ?? ()
#28 0x8b80b9e10a9381d1 in ?? ()
#29 0x4e441c8f568e1596 in ?? ()
#30 0x84700a0163e36b27 in ?? ()
#31 0xb9d1e924dda1d83a in ?? ()
#32 0x5404a7d8fe0140d3 in ?? ()
#33 0x6d51cd3c86ec5c11 in ?? ()
#34 0x818518812e5bad87 in ?? ()
#35 0xbb10c22507af012a in ?? ()
#36 0x91fb8c125f75b248 in ?? ()
#37 0xb63491c47e13b11f in ?? ()
#38 0x96ba1fed1b69c364 in ?? ()
#39 0xfed75ea792413f6a in ?? ()
#40 0xc494860a4ba9491c in ?? ()
#41 0x6324e3e4475335b8 in ?? ()
#42 0xdf9152721183c0a3 in ?? ()
---Type <return> to continue, or q <return> to quit---
#43 0xccd726fde929022a in ?? ()
#44 0xbede27a9d6bd2601 in ?? ()
#45 0x35bf1fdae0c849d8 in ?? ()
#46 0xa3e6d3a74973d63f in ?? ()
#47 0x3aa3d3616f4947da in ?? ()
#48 0x035c5609cbb26f37 in ?? ()
#49 0x32fac3664b711206 in ?? ()
#50 0xc47ff1f19696a626 in ?? ()
#51 0x80e2aa45397c1407 in ?? ()
#52 0x812ca0056d78d4e0 in ?? ()
#53 0xa11bef1ee11fcad9 in ?? ()
#54 0x25071fe0be3f6f0c in ?? ()
#55 0xa34d2172c1e08994 in ?? ()
#56 0x2efd5ae00542660c in ?? ()
#57 0xe0a5a3fa62aa98fb in ?? ()
#58 0x09f2fbc723226334 in ?? ()
#59 0x9f7a98dab1ed9104 in ?? ()
#60 0x09d64317d7cb1bef in ?? ()
#61 0x88618058a6b82bc7 in ?? ()
#62 0xcb3cc048b449a2c4 in ?? ()
#63 0x7a2e324ca8cc32ce in ?? ()
#64 0x1b88c838b261c414 in ?? ()
#65 0x00007f70461d31e0 in ?? ()
#66 0x00007f6fd4129210 in ?? ()
#67 0x00007f6fd41c7910 in ?? ()
#68 0x00007f70461d3108 in ?? ()
#69 0x0000000000000000 in ?? ()
```

Maybe an OpenSSL error (bad instruction / stack broken). Maybe not...

**Comment by Al2Klimov** [comment]
Maybe you give a more recent OS (+OpenSSL) version a try? After all 16.04 isn't listed even in https://packages.ubuntu.com anymore.

**Comment by maelig** [comment]
`


BACKUP | root@slg-infra-prd-azu-frw-lnx-icinga-002:~ # dpkg -l |grep ssl
ii  libgnutls-openssl27:amd64                   3.4.10-4ubuntu1.7                          amd64        GNU TLS library - OpenSSL wrapper
ii  libssl1.0.0:amd64                           1.0.2g-1ubuntu4.20                         amd64        Secure Sockets Layer toolkit - shared libraries
ii  libxmlsec1-openssl                          1.2.20-2ubuntu4                            amd64        Openssl engine for the XML security library
ii  openssl                                     1.0.2g-1ubuntu4.20                         amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  ssl-cert                                    1.0.37                                     all          simple debconf wrapper for OpenSSL
```

**Comment by maelig** [comment]
Perhaps upgrading to Ubuntu 20 will fix the bug?

**Comment by Al2Klimov** [comment]
You name it.

**Comment by maelig** [comment]
Sorry for the delay but it's resolved since migrating to ubuntu 20.
