### ISSUE TITLE
GelfWriter: socket write/flush has no timeout

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga2#9859]
## Describe the bug

The socket write and flush operations in `GelfWriter` don't have any sort of timeout. Because Icinga 2 waits for the queue to be flushed on reload/shutdown, this means that this can be slowed down arbitrarily by a slow server.

## To Reproduce

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include configuration, logs, etc. to reproduce, if relevant.

1. Start an intentionally broken dummy server that accepts connections but doesn't read data from the connection: `nc -l -p 12201 | sleep inf`
2. Configure a `GelfWriter` that connects to that server.
3. Start Icinga 2 (the config should have some hosts/services that produce events for `GelfWriter`).
4. Wait for all queues to fill up (at some point, you should see log messages of the `WorkQueue` filling up, to be extra sure, you can also use `strace` to check there are no new writes to the socket fd.)
5. Send SIGHUP to Icinga 2 to trigger a reload.

When looking at the threads with gdb, there is one thread that's blocked in writing to that socket and the Icinga 2 process never reloads:

```
Thread 17 (Thread 0x7fe5ba961700 (LWP 13622) "icinga2"):
#0  __libc_send (flags=<optimized out>, len=98, buf=0x7fe584003c7c, fd=20) at ../sysdeps/unix/sysv/linux/send.c:28
#1  __libc_send (fd=20, buf=0x7fe584003c7c, len=98, flags=16384) at ../sysdeps/unix/sysv/linux/send.c:23
#2  0x000055f4fa18b235 in boost::asio::detail::socket_ops::send1(int, void const*, unsigned long, int, boost::system::error_code&) ()
#3  0x000055f4fa18b2f1 in boost::asio::detail::socket_ops::sync_send1(int, unsigned char, void const*, unsigned long, int, boost::system::error_code&) ()
#4  0x000055f4fa192100 in unsigned long boost::asio::detail::reactive_socket_service_base::send<boost::asio::const_buffers_1>(boost::asio::detail::reactive_socket_service_base::base_implementation_type&, boost::asio::const_buffers_1 const&, int, boost::system::error_code&) ()
#5  0x000055f4fa191509 in unsigned long boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>::write_some<boost::asio::const_buffers_1>(boost::asio::const_buffers_1 const&, boost::system::error_code&) ()
#6  0x000055f4faa6c60b in unsigned long boost::asio::detail::write_buffer_sequence<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t>(boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>&, boost::asio::mutable_buffers_1 const&, boost::asio::mutable_buffer const* const&, boost::asio::detail::transfer_all_t, boost::system::error_code&) ()
#7  0x000055f4faa6aa57 in unsigned long boost::asio::write<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t>(boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>&, boost::asio::mutable_buffers_1 const&, boost::asio::detail::transfer_all_t, boost::system::error_code&, std::enable_if<boost::asio::is_const_buffer_sequence<boost::asio::mutable_buffers_1>::value, void>::type*) ()
#8  0x000055f4faa69587 in unsigned long boost::asio::write<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1>(boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>&, boost::asio::mutable_buffers_1 const&, std::enable_if<boost::asio::is_const_buffer_sequence<boost::asio::mutable_buffers_1>::value, void>::type*) ()
#9  0x000055f4faa68749 in boost::asio::buffered_write_stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor> >::flush() ()
#10 0x000055f4faa6779c in boost::asio::buffered_stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor> >::flush() ()
#11 0x000055f4faa7e8c0 in icinga::GelfWriter::SendLogMessage(boost::intrusive_ptr<icinga::Checkable> const&, icinga::String const&) ()
#12 0x000055f4faa7b51c in icinga::GelfWriter::CheckResultHandlerInternal(boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&) ()
#13 0x000055f4faa79c64 in icinga::GelfWriter::CheckResultHandler(boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&)::{lambda()#1}::operator()() const ()
#14 0x000055f4faa84b00 in void std::__invoke_impl<void, icinga::GelfWriter::CheckResultHandler(boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&)::{lambda()#1}&>(std::__invoke_other, icinga::GelfWriter::CheckResultHandler(boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&)::{lambda()#1}&) ()
#15 0x000055f4faa83111 in std::enable_if<is_invocable_r_v<void, icinga::GelfWriter::CheckResultHandler(boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&)::{lambda()#1}&>, void>::type std::__invoke_r<void, icinga::GelfWriter::CheckResultHandler(boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&)::{lambda()#1}&>(icinga::GelfWriter::CheckResultHandler(boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&)::{lambda()#1}&) ()
#16 0x000055f4faa80ed7 in std::_Function_handler<void (), icinga::GelfWriter::CheckResultHandler(boost::intrusive_ptr<icinga::Checkable> const&, boost::intrusive_ptr<icinga::CheckResult> const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#17 0x000055f4fa174a16 in std::function<void ()>::operator()() const ()
#18 0x000055f4fa272041 in icinga::WorkQueue::RunTaskFunction(std::function<void ()> const&) ()
#19 0x000055f4fa2723c6 in icinga::WorkQueue::WorkerThreadProc() ()
#20 0x000055f4fa2711e3 in icinga::WorkQueue::EnqueueUnlocked(std::unique_lock<std::mutex>&, std::function<void ()>&&, icinga::WorkQueuePriority)::{lambda()#1}::operator()() const ()
#21 0x000055f4fa2734c4 in boost::detail::thread_data<icinga::WorkQueue::EnqueueUnlocked(std::unique_lock<std::mutex>&, std::function<void ()>&&, icinga::WorkQueuePriority)::{lambda()#1}>::run() ()
#22 0x00007fe5be23e787 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.74.0
#23 0x00007fe5bdccbea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#24 0x00007fe5bd8bea2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

## Your Environment

Tested with 4ee10a6c20802ecc2d1f933f4686334a7626deec from #9853 in Docker. Without that PR, a deadlock will happen instead. With that PR, things work fine if the server can keep up, this issue is for when the server doesn't.

**Comment by martialblog** [comment]
@jschmidt-icinga Hi, I think this was fixed with https://github.com/Icinga/icinga2/pull/10668 right? The Writer now has a 10s timeout by default.

**Comment by jschmidt-icinga** [comment]
@martialblog Yes, this should be fixed for all writers. The timeout defined in the writer config will also abort the connection and discard all entries for writers that aren't offline, but just slow or backed up.

I remembered there was another issue that's essentially a duplicate of #10159, but I couldn't find it when I created #10668.
