### ISSUE TITLE
Checking the input Performance Data for Quotes to avoid crashing the entire service page in IcingaWeb2

### ISSUE THREAD

**Issue by adamparker** [Icinga/icinga2#9869]
## Describe the bug

I was playing around with the API and using the web based submit check result I submitted the following to a passive check (note the escaping nonsense at the start):

plugin output: DISK OK - free space: / 3326 MB (56%);
performance data: "'/'=2645.0MB;5948.0;5958.0;0.0;5968.0; 'temp'=35C;10:40;5:45;

Service definition:

apply Service "check_passive_test" {
  import "generic-service"

  name = "15m_checkPassiveTest"
  display_name = "Check Passive Test"
  check_interval = 15m
  
  enable_active_checks = false
 
  check_command = "dummy"
  vars.dummy_text = "No Passive Check Result Received"
  vars.dummy_state = "3"

  assign where host.address == "192.168.1.1" // this was changed
}

And it crashed the icingaweb2 parser so that everytime the service was loaded, it came up with:

''''
Uninitialized string offset: 61

#0 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Util/PerfDataSet.php(121): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}()
#1 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Util/PerfDataSet.php(84): Icinga\Module\Icingadb\Util\PerfDataSet->readLabel()
#2 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Util/PerfDataSet.php(42): Icinga\Module\Icingadb\Util\PerfDataSet->parse()
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Util/PerfDataSet.php(65): Icinga\Module\Icingadb\Util\PerfDataSet->__construct()
#4 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/PerfDataTable.php(51): Icinga\Module\Icingadb\Util\PerfDataSet::fromString()
#5 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(295): Icinga\Module\Icingadb\Widget\Detail\PerfDataTable->assemble()
#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(497): ipl\Html\HtmlDocument->ensureAssembled()
#7 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\BaseHtmlElement->renderUnwrapped()
#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#14 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\BaseHtmlElement->renderUnwrapped()
#15 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#16 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#17 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#18 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\BaseHtmlElement->renderUnwrapped()
#19 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#20 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\HtmlDocument->renderUnwrapped()
#21 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/ViewRenderer.php(56): ipl\Html\HtmlDocument->render()
#22 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): ipl\Web\Compat\ViewRenderer->render()
#23 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#24 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(506): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#25 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch()
#26 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#27 /usr/share/icingaweb2/library/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#28 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#29 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#30 {main}
''''

The performance data when requested by the API looked like this:
```
                    "performance_data": [
                        "\"'/'=2645.0MB;5948.0;5958.0;0.0;5968.0;",
                        "temp=35C;10:40;5:45;"
                    ],
```

It can be fixed by submitting a new result, by curl without the quotation mark at the start and the issue goes away.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: v2.14.0)

Copyright (c) 2012-2023 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 11 (bullseye)
  Kernel: Linux
  Kernel version: 4.19.0-16-amd64
  Architecture: x86_64

Icinga Web 2 Version | 2.11.4

**Comment by Al2Klimov** [comment]
@nilmerg Feel free to transfer this to DB Web if you think it shall not crash in this case.
